//
// InDesign Document Query Tool v3.0 - Complete Combined Build
// Modular Architecture - All Modules Assembled
// Generated: 2025-06-15T06:27:27.487Z
// 
// This file contains 5 modules assembled in order:
// Module 1 (v1.0): Module_1.0_ConfigAndSafety.jsx
// Module 2 (v2.0): Module_2.0_DocumentAnalysisAndTreeBuilder.jsx
// Module 3 (v3.0): Module_3.0_UIPanelAndControls.jsx
// Module 4 (v4.0): Module_4.0_ExportAndResultsDisplay.jsx
// Module 5 (v5.0): Module_5.0_MainEntryPoint.jsx
//
// USAGE: Run this script in InDesign or ESTK for configurable document querying
// All modules are self-contained and execute in proper order
//
// DO NOT EDIT THIS FILE DIRECTLY - Edit individual module files instead
//

// Module Loading Verification
var MODULES_LOADED = [];
function verifyModuleLoad(itemName) {
    MODULES_LOADED.push(itemName);
    $.writeln("✓ Module loaded: " + itemName);
}

// ==============================================================================
// MODULE 1 (v1.0): MODULE_1.0_CONFIGANDSAFETY.JSX
// ==============================================================================

verifyModuleLoad("Module_1.0_ConfigAndSafety");

// ============================================================================
// MODULE 1.0: CORE CONFIGURATION & SAFETY FRAMEWORK
// InDesign Document Query Tool v3.0 - Configurable Analysis
// ES3 Compatible - Lightweight & Targeted
// ============================================================================

// QUERY TOOL CONFIGURATION - Simplified and Focused
var QUERY_CONFIG = {
    version: "3.0-query-tool",
    
    // Analysis targets with user control
    targets: {
        documentProperties: { enabled: true, safe: true, timeout: 100 },
        pages: { enabled: true, safe: true, timeout: 200 },
        textFrames: { enabled: true, safe: true, timeout: 300 },
        stories: { enabled: true, safe: false, timeout: 500 },
        layers: { enabled: true, safe: true, timeout: 150 },
        images: { enabled: false, safe: false, timeout: 1000 },
        links: { enabled: false, safe: false, timeout: 1000 },
        pageItems: { enabled: false, safe: false, timeout: 800 },
        styles: { enabled: true, safe: true, timeout: 300 },
        colors: { enabled: true, safe: true, timeout: 200 },
        fonts: { enabled: true, safe: true, timeout: 200 },
        masterPages: { enabled: false, safe: false, timeout: 400 }
    },
    
    // Traversal settings
    traversal: {
        maxDepth: 3,
        sampleLimit: 10,
        timeoutMs: 500,
        showEmpty: true,
        showNull: true,
        showBroken: true,
        verboseProgress: true,
        pathTracking: true,
        emergencyBailouts: true
    },
    
    // Progress tracking
    progress: {
        currentTarget: "",
        currentPath: "",
        totalTargets: 0,
        completedTargets: 0,
        currentResult: "",
        status: "ready"
    },
    
    // File paths
    paths: {
        documentPath: "",
        outputPath: "",
        currentDocument: null
    },
    
    // Runtime state
    runtime: {
        analysisActive: false,
        startTime: 0,
        results: {},
        progressCallback: null
    }
};

// PROGRESS TRACKING SYSTEM - Visual feedback for user
function updateProgress(target, path, result, status) {
    QUERY_CONFIG.progress.currentTarget = target || "";
    QUERY_CONFIG.progress.currentPath = path || "";
    QUERY_CONFIG.progress.currentResult = result || "";
    QUERY_CONFIG.progress.status = status || "working";
    
    // Update progress percentage
    if (QUERY_CONFIG.progress.totalTargets > 0) {
        var percentage = Math.round((QUERY_CONFIG.progress.completedTargets / QUERY_CONFIG.progress.totalTargets) * 100);
        QUERY_CONFIG.progress.percentage = percentage;
    }
    
    // Call progress callback if set (for UI updates)
    if (QUERY_CONFIG.runtime.progressCallback && typeof QUERY_CONFIG.runtime.progressCallback === 'function') {
        QUERY_CONFIG.runtime.progressCallback(QUERY_CONFIG.progress);
    }
    
    // Console logging for ESTK debugging
    var timestamp = new Date().toLocaleTimeString();
    var resultSymbol = getResultSymbol(result, status);
    $.writeln("[QUERY] [" + timestamp + "] " + target + ": " + path + " → " + result + " " + resultSymbol);
}

function getResultSymbol(result, status) {
    if (status === "error" || status === "timeout") return "✗";
    if (status === "empty" || status === "null") return "⚠";
    if (status === "success" || result) return "✓";
    return "?";
}

// SAFE PROPERTY ACCESS - Inherited from chunk wisdom
function queryGetProperty(obj, prop, defaultValue) {
    var startTime = new Date().getTime();
    var timeout = QUERY_CONFIG.traversal.timeoutMs;
    var path = "obj." + prop;
    
    try {
        updateProgress("property", path, "accessing...", "working");
        
        if (!obj) {
            updateProgress("property", path, "null object", "null");
            return { value: null, status: "null_object", path: path };
        }
        
        // Check timeout
        if (new Date().getTime() - startTime > timeout) {
            updateProgress("property", path, "TIMEOUT", "timeout");
            return { value: defaultValue, status: "timeout", path: path };
        }
        
        var value = null;
        
        // Try hasOwnProperty first (safest)
        if (obj.hasOwnProperty && obj.hasOwnProperty(prop)) {
            value = obj[prop];
        } else if (obj[prop] !== undefined) {
            value = obj[prop];
        }
        
        var result = analyzeValue(value, path);
        updateProgress("property", path, result.description, result.status);
        
        return {
            value: value,
            status: result.status,
            type: result.type,
            description: result.description,
            path: path,
            processingTime: new Date().getTime() - startTime
        };
        
    } catch (exc) {
        updateProgress("property", path, "ERROR: " + exc.message, "error");
        return { 
            value: defaultValue, 
            status: "error", 
            error: exc.message, 
            path: path,
            processingTime: new Date().getTime() - startTime
        };
    }
}

function analyzeValue(value, path) {
    if (value === null) {
        return { status: "null", type: "null", description: "null" };
    }
    if (value === undefined) {
        return { status: "undefined", type: "undefined", description: "undefined" };
    }
    if (value === "") {
        return { status: "empty", type: "string", description: "empty string" };
    }
    if (typeof value === "string") {
        var preview = value.length > 50 ? value.substring(0, 50) + "..." : value;
        return { status: "success", type: "string", description: '"' + preview + '"' };
    }
    if (typeof value === "number") {
        return { status: "success", type: "number", description: value.toString() };
    }
    if (typeof value === "boolean") {
        return { status: "success", type: "boolean", description: value.toString() };
    }
    if (typeof value === "object" && value.constructor === Array) {
        return { status: "success", type: "array", description: "Array[" + value.length + "]" };
    }
    if (typeof value === "object") {
        return { status: "success", type: "object", description: "Object{...}" };
    }
    
    return { status: "success", type: typeof value, description: String(value) };
}

// SAFE COLLECTION ACCESS - Inherited wisdom with query focus
function queryGetCollection(doc, collectionName) {
    var target = QUERY_CONFIG.targets[collectionName];
    if (!target || !target.enabled) {
        updateProgress(collectionName, "doc." + collectionName, "DISABLED", "disabled");
        return { collection: null, status: "disabled", reason: "Collection disabled in config" };
    }
    
    var startTime = new Date().getTime();
    var timeout = target.timeout || QUERY_CONFIG.traversal.timeoutMs;
    var path = "doc." + collectionName;
    
    try {
        updateProgress(collectionName, path, "accessing collection...", "working");
        
        // Quick timeout check for dangerous collections
        if (!target.safe && timeout > 200) {
            timeout = 200; // Force shorter timeout for unsafe collections
        }
        
        if (new Date().getTime() - startTime > timeout) {
            updateProgress(collectionName, path, "TIMEOUT", "timeout");
            return { collection: null, status: "timeout", reason: "Collection access timeout" };
        }
        
        var collection = doc[collectionName];
        
        if (!collection) {
            updateProgress(collectionName, path, "NULL", "null");
            return { collection: null, status: "null", reason: "Collection is null" };
        }
        
        // Get length safely
        var length = 0;
        try {
            if (typeof collection.length === 'number') {
                length = collection.length;
            } else if (typeof collection.count === 'number') {
                length = collection.count;
            }
        } catch (lengthError) {
            updateProgress(collectionName, path, "LENGTH ERROR", "error");
            return { collection: null, status: "error", reason: "Cannot get collection length" };
        }
        
        updateProgress(collectionName, path, "Collection[" + length + "]", "success");
        
        return {
            collection: collection,
            status: "success",
            length: length,
            path: path,
            processingTime: new Date().getTime() - startTime
        };
        
    } catch (exc) {
        updateProgress(collectionName, path, "ERROR: " + exc.message, "error");
        return { 
            collection: null, 
            status: "error", 
            error: exc.message, 
            reason: "Collection access failed",
            path: path,
            processingTime: new Date().getTime() - startTime
        };
    }
}

// DOM TREE NODE CREATION - Structure for tree output
function createTreeNode(name, value, type, status, path, children) {
    return {
        name: name || "unknown",
        value: value,
        type: type || "unknown",
        status: status || "unknown",
        path: path || "",
        children: children || [],
        hasChildren: children && children.length > 0,
        expanded: false,
        depth: (path.split('.').length - 1)
    };
}

// EMERGENCY BAILOUT - Prevent hanging with timeout wrapper
function queryEmergencyBailout(operation, timeoutMs, operationName) {
    var startTime = new Date().getTime();
    var timeout = timeoutMs || QUERY_CONFIG.traversal.timeoutMs;
    var name = operationName || "operation";
    
    updateProgress("bailout", name, "starting...", "working");
    
    try {
        var result = operation();
        var duration = new Date().getTime() - startTime;
        
        if (duration > timeout) {
            updateProgress("bailout", name, "TIMEOUT (" + duration + "ms)", "timeout");
            return { bailout: true, duration: duration, timeout: timeout, result: null };
        }
        
        updateProgress("bailout", name, "completed (" + duration + "ms)", "success");
        return { bailout: false, duration: duration, result: result };
        
    } catch (exc) {
        var duration = new Date().getTime() - startTime;
        updateProgress("bailout", name, "ERROR: " + exc.message, "error");
        return { bailout: true, duration: duration, error: exc.message, result: null };
    }
}

// CONFIGURATION PRESETS - Quick setup options
var QUERY_PRESETS = {
    basicSafe: {
        name: "Basic Safe",
        description: "Only safe collections with minimal depth",
        config: {
            targets: ["documentProperties", "pages", "layers"],
            maxDepth: 2,
            sampleLimit: 5,
            timeoutMs: 300
        }
    },
    
    textOnly: {
        name: "Text Analysis",
        description: "Focus on text content and frames",
        config: {
            targets: ["documentProperties", "textFrames", "stories", "styles", "fonts"],
            maxDepth: 3,
            sampleLimit: 10,
            timeoutMs: 500
        }
    },
    
    fullScan: {
        name: "Complete Scan",
        description: "All available collections with safety limits",
        config: {
            targets: ["documentProperties", "pages", "textFrames", "stories", "layers", "styles", "colors", "fonts"],
            maxDepth: 4,
            sampleLimit: 15,
            timeoutMs: 800
        }
    }
};

function applyPreset(presetName) {
    var preset = QUERY_PRESETS[presetName];
    if (!preset) return false;
    
    // Disable all targets first
    for (var target in QUERY_CONFIG.targets) {
        QUERY_CONFIG.targets[target].enabled = false;
    }
    
    // Enable preset targets
    for (var i = 0; i < preset.config.targets.length; i++) {
        var targetName = preset.config.targets[i];
        if (QUERY_CONFIG.targets[targetName]) {
            QUERY_CONFIG.targets[targetName].enabled = true;
        }
    }
    
    // Apply other settings
    QUERY_CONFIG.traversal.maxDepth = preset.config.maxDepth;
    QUERY_CONFIG.traversal.sampleLimit = preset.config.sampleLimit;
    QUERY_CONFIG.traversal.timeoutMs = preset.config.timeoutMs;
    
    updateProgress("preset", presetName, "applied", "success");
    return true;
}

// UTILITY FUNCTIONS - ES3 compatible helpers
function getEnabledTargets() {
    var enabled = [];
    for (var target in QUERY_CONFIG.targets) {
        if (QUERY_CONFIG.targets[target].enabled) {
            enabled.push(target);
        }
    }
    return enabled;
}

function resetProgress() {
    QUERY_CONFIG.progress.currentTarget = "";
    QUERY_CONFIG.progress.currentPath = "";
    QUERY_CONFIG.progress.currentResult = "";
    QUERY_CONFIG.progress.completedTargets = 0;
    QUERY_CONFIG.progress.totalTargets = 0;
    QUERY_CONFIG.progress.percentage = 0;
    QUERY_CONFIG.progress.status = "ready";
}

function isAnalysisActive() {
    return QUERY_CONFIG.runtime.analysisActive;
}

$.writeln("Module A: Core Configuration & Safety Framework loaded");

// ==============================================================================
// MODULE 2 (v2.0): MODULE_2.0_DOCUMENTANALYSISANDTREEBUILDER.JSX
// ==============================================================================

verifyModuleLoad("Module_2.0_DocumentAnalysisAndTreeBuilder");

// ============================================================================
// MODULE 2.0: DOCUMENT ANALYSIS & TREE BUILDER
// InDesign Document Query Tool v3.0 - Configurable Analysis
// ES3 Compatible - DOM Tree Generation with Progress Tracking
// ============================================================================

// MAIN ANALYSIS FUNCTION - Entry point for document querying
function analyzeDocumentToTree(doc) {
    if (!doc) {
        updateProgress("analysis", "document", "No document provided", "error");
        return null;
    }
    
    // Reset and prepare
    resetProgress();
    QUERY_CONFIG.runtime.analysisActive = true;
    QUERY_CONFIG.runtime.startTime = new Date().getTime();
    QUERY_CONFIG.runtime.results = {};
    
    var enabledTargets = getEnabledTargets();
    QUERY_CONFIG.progress.totalTargets = enabledTargets.length;
    
    updateProgress("analysis", "document", "Starting analysis of " + enabledTargets.length + " targets", "working");
    
    // Create root tree node
    var documentTree = createTreeNode(
        "Document",
        "InDesign Document",
        "document",
        "success",
        "doc",
        []
    );
    
    // Process each enabled target
    for (var i = 0; i < enabledTargets.length; i++) {
        var targetName = enabledTargets[i];
        
        updateProgress("analysis", targetName, "Analyzing target " + (i + 1) + " of " + enabledTargets.length, "working");
        
        try {
            var targetNode = analyzeTarget(doc, targetName);
            if (targetNode) {
                documentTree.children.push(targetNode);
            }
            
            QUERY_CONFIG.progress.completedTargets++;
            updateProgress("analysis", targetName, "Target completed", "success");
            
        } catch (exc) {
            updateProgress("analysis", targetName, "Target failed: " + exc.message, "error");
            
            // Add error node
            var errorNode = createTreeNode(
                targetName,
                "ERROR: " + exc.message,
                "error",
                "error",
                "doc." + targetName,
                []
            );
            documentTree.children.push(errorNode);
        }
    }
    
    // Finalize
    var totalTime = new Date().getTime() - QUERY_CONFIG.runtime.startTime;
    updateProgress("analysis", "complete", "Analysis completed in " + totalTime + "ms", "success");
    
    QUERY_CONFIG.runtime.analysisActive = false;
    return documentTree;
}

// TARGET ANALYSIS - Handle different types of document elements
function analyzeTarget(doc, targetName) {
    var startTime = new Date().getTime();
    var targetPath = "doc." + targetName;
    
    updateProgress(targetName, targetPath, "starting target analysis", "working");
    
    // Special handling for different target types
    switch (targetName) {
        case "documentProperties":
            return analyzeDocumentProperties(doc);
        case "pages":
        case "textFrames":
        case "stories":
        case "layers":
        case "images":
        case "links":
        case "pageItems":
        case "styles":
        case "colors":
        case "fonts":
        case "masterPages":
            return analyzeCollection(doc, targetName);
        default:
            updateProgress(targetName, targetPath, "Unknown target type", "error");
            return null;
    }
}

// DOCUMENT PROPERTIES ANALYSIS - Extract core document info
function analyzeDocumentProperties(doc) {
    var startTime = new Date().getTime();
    var docPath = "doc.properties";
    
    updateProgress("documentProperties", docPath, "analyzing document properties", "working");
    
    var propertiesNode = createTreeNode(
        "Document Properties",
        "Core document information",
        "properties",
        "success",
        docPath,
        []
    );
    
    // Essential properties to check
    var essentialProps = [
        { name: "name", safe: true },
        { name: "saved", safe: true },
        { name: "modified", safe: true },
        { name: "visible", safe: true },
        { name: "id", safe: true },
        { name: "filePath", safe: false },
        { name: "readonly", safe: false }
    ];
    
    for (var i = 0; i < essentialProps.length; i++) {
        var prop = essentialProps[i];
        var propPath = docPath + "." + prop.name;
        
        // Skip unsafe properties if emergency bailouts enabled
        if (!prop.safe && QUERY_CONFIG.traversal.emergencyBailouts) {
            var skipNode = createTreeNode(
                prop.name,
                "SKIPPED (unsafe)",
                "skipped",
                "skipped",
                propPath,
                []
            );
            propertiesNode.children.push(skipNode);
            continue;
        }
        
        var propResult = queryGetProperty(doc, prop.name, null);
        var propNode = createTreeNode(
            prop.name,
            propResult.description || propResult.value,
            propResult.type,
            propResult.status,
            propPath,
            []
        );
        
        propertiesNode.children.push(propNode);
    }
    
    var duration = new Date().getTime() - startTime;
    updateProgress("documentProperties", docPath, "properties analyzed (" + duration + "ms)", "success");
    
    return propertiesNode;
}

// COLLECTION ANALYSIS - Handle InDesign collections with safety
function analyzeCollection(doc, collectionName) {
    var startTime = new Date().getTime();
    var collectionPath = "doc." + collectionName;
    
    updateProgress(collectionName, collectionPath, "accessing collection", "working");
    
    var collectionResult = queryGetCollection(doc, collectionName);
    
    if (collectionResult.status !== "success") {
        // Return error/disabled/timeout node
        return createTreeNode(
            collectionName,
            collectionResult.reason || "Collection inaccessible",
            "collection",
            collectionResult.status,
            collectionPath,
            []
        );
    }
    
    var collection = collectionResult.collection;
    var length = collectionResult.length;
    
    // Create collection node
    var collectionNode = createTreeNode(
        collectionName,
        "Collection[" + length + "]",
        "collection",
        "success",
        collectionPath,
        []
    );
    
    if (length === 0) {
        var emptyNode = createTreeNode(
            "empty",
            "No items in collection",
            "empty",
            "empty",
            collectionPath + ".empty",
            []
        );
        collectionNode.children.push(emptyNode);
        return collectionNode;
    }
    
    // Sample items from collection
    var sampleLimit = Math.min(length, QUERY_CONFIG.traversal.sampleLimit);
    var itemTimeout = QUERY_CONFIG.targets[collectionName].timeout / sampleLimit;
    
    updateProgress(collectionName, collectionPath, "sampling " + sampleLimit + " items", "working");
    
    for (var i = 0; i < sampleLimit; i++) {
        var itemPath = collectionPath + "[" + i + "]";
        
        try {
            updateProgress(collectionName, itemPath, "processing item " + (i + 1), "working");
            
            var itemResult = queryEmergencyBailout(function() {
                try {
                    return collection[i];
                } catch (e1) {
                    if (collection.item) {
                        return collection.item(i);
                    }
                    throw e1;
                }
            }, itemTimeout, "collection[" + i + "]");
            
            if (itemResult.bailout) {
                var bailoutNode = createTreeNode(
                    "[" + i + "]",
                    "TIMEOUT/ERROR",
                    "error",
                    "timeout",
                    itemPath,
                    []
                );
                collectionNode.children.push(bailoutNode);
                continue;
            }
            
            var item = itemResult.result;
            if (!item) {
                var nullNode = createTreeNode(
                    "[" + i + "]",
                    "null item",
                    "null",
                    "null",
                    itemPath,
                    []
                );
                collectionNode.children.push(nullNode);
                continue;
            }
            
            // Analyze the item
            var itemNode = analyzeCollectionItem(item, i, itemPath, collectionName);
            collectionNode.children.push(itemNode);
            
        } catch (exc) {
            var errorNode = createTreeNode(
                "[" + i + "]",
                "ERROR: " + exc.message,
                "error",
                "error",
                itemPath,
                []
            );
            collectionNode.children.push(errorNode);
        }
    }
    
    // Add truncation note if we didn't process all items
    if (sampleLimit < length) {
        var truncateNode = createTreeNode(
            "...",
            "+" + (length - sampleLimit) + " more items (use higher sample limit)",
            "truncated",
            "truncated",
            collectionPath + ".truncated",
            []
        );
        collectionNode.children.push(truncateNode);
    }
    
    var duration = new Date().getTime() - startTime;
    updateProgress(collectionName, collectionPath, "collection analyzed (" + duration + "ms)", "success");
    
    return collectionNode;
}

// COLLECTION ITEM ANALYSIS - Analyze individual items in collections
function analyzeCollectionItem(item, index, itemPath, collectionType) {
    var itemName = "[" + index + "]";
    
    // Get item type/constructor name
    var itemType = "unknown";
    try {
        if (item.constructor && item.constructor.name) {
            itemType = item.constructor.name;
        }
    } catch (e) {
        itemType = "unknown";
    }
    
    // Create item node
    var itemNode = createTreeNode(
        itemName,
        itemType,
        "item",
        "success",
        itemPath,
        []
    );
    
    // Stop here if we've reached max depth
    if (itemNode.depth >= QUERY_CONFIG.traversal.maxDepth) {
        var depthNode = createTreeNode(
            "...",
            "Max depth reached",
            "depth_limit",
            "truncated",
            itemPath + ".depth_limit",
            []
        );
        itemNode.children.push(depthNode);
        return itemNode;
    }
    
    // Get key properties based on collection type
    var keyProperties = getKeyPropertiesForCollection(collectionType);
    
    for (var i = 0; i < keyProperties.length; i++) {
        var propName = keyProperties[i];
        var propPath = itemPath + "." + propName;
        
        var propResult = queryGetProperty(item, propName, null);
        
        // Skip null/empty if not configured to show them
        if (propResult.status === "null" && !QUERY_CONFIG.traversal.showNull) continue;
        if (propResult.status === "empty" && !QUERY_CONFIG.traversal.showEmpty) continue;
        
        var propNode = createTreeNode(
            propName,
            propResult.description || String(propResult.value),
            propResult.type,
            propResult.status,
            propPath,
            []
        );
        
        itemNode.children.push(propNode);
    }
    
    return itemNode;
}

// KEY PROPERTIES - Define important properties per collection type
function getKeyPropertiesForCollection(collectionType) {
    var propertyMap = {
        pages: ["name", "bounds", "side", "documentOffset"],
        textFrames: ["id", "bounds", "overflows", "contents"],
        stories: ["id", "length", "overflows"],
        layers: ["name", "visible", "locked", "layerColor"],
        images: ["id", "bounds", "actualPpi", "effectivePpi"],
        links: ["name", "status", "filePath", "size"],
        pageItems: ["id", "bounds", "visible", "locked"],
        styles: ["name", "basedOn"],
        colors: ["name", "model", "colorValue"],
        fonts: ["name", "fontFamily", "status"],
        masterPages: ["name", "bounds"]
    };
    
    return propertyMap[collectionType] || ["name", "id"];
}

// TREE TRAVERSAL UTILITIES - Helper functions for tree manipulation
function countTreeNodes(treeNode) {
    if (!treeNode) return 0;
    
    var count = 1; // Count this node
    
    if (treeNode.children && treeNode.children.length > 0) {
        for (var i = 0; i < treeNode.children.length; i++) {
            count += countTreeNodes(treeNode.children[i]);
        }
    }
    
    return count;
}

function findNodeByPath(treeNode, targetPath) {
    if (!treeNode || !targetPath) return null;
    
    if (treeNode.path === targetPath) {
        return treeNode;
    }
    
    if (treeNode.children && treeNode.children.length > 0) {
        for (var i = 0; i < treeNode.children.length; i++) {
            var found = findNodeByPath(treeNode.children[i], targetPath);
            if (found) return found;
        }
    }
    
    return null;
}

function getTreeStatistics(treeNode) {
    var stats = {
        totalNodes: 0,
        successNodes: 0,
        errorNodes: 0,
        nullNodes: 0,
        emptyNodes: 0,
        timeoutNodes: 0,
        maxDepth: 0
    };
    
    function traverseForStats(node, depth) {
        stats.totalNodes++;
        stats.maxDepth = Math.max(stats.maxDepth, depth);
        
        switch (node.status) {
            case "success": stats.successNodes++; break;
            case "error": stats.errorNodes++; break;
            case "null": stats.nullNodes++; break;
            case "empty": stats.emptyNodes++; break;
            case "timeout": stats.timeoutNodes++; break;
        }
        
        if (node.children && node.children.length > 0) {
            for (var i = 0; i < node.children.length; i++) {
                traverseForStats(node.children[i], depth + 1);
            }
        }
    }
    
    if (treeNode) {
        traverseForStats(treeNode, 0);
    }
    
    return stats;
}

$.writeln("Module B: Document Analysis & Tree Builder loaded");

// ==============================================================================
// MODULE 3 (v3.0): MODULE_3.0_UIPANELANDCONTROLS.JSX
// ==============================================================================

verifyModuleLoad("Module_3.0_UIPanelAndControls");

// ============================================================================
// MODULE 3.0: UI PANEL & CONTROLS
// InDesign Document Query Tool v3.0 - Configurable Analysis
// ES3 Compatible - Landscape Panel Interface
// ============================================================================

// UI STATE MANAGEMENT
var UI_STATE = {
    mainDialog: null,
    progressText: null,
    progressBar: null,
    statusText: null,
    resultTree: null,
    targetCheckboxes: {},
    configControls: {},
    currentResults: null
};

// MAIN UI CREATION - Landscape wide panel
function createMainInterface() {
    // Create main dialog
    UI_STATE.mainDialog = new Window("dialog", "InDesign Document Query Tool v3.0");
    UI_STATE.mainDialog.orientation = "column";
    UI_STATE.mainDialog.alignChildren = "fill";
    UI_STATE.mainDialog.preferredSize.width = 900;
    UI_STATE.mainDialog.preferredSize.height = 650;
    
    // File paths panel
    createFilePathPanel(UI_STATE.mainDialog);
    
    // Target selection panel
    createTargetSelectionPanel(UI_STATE.mainDialog);
    
    // Configuration panel
    createConfigurationPanel(UI_STATE.mainDialog);
    
    // Progress panel
    createProgressPanel(UI_STATE.mainDialog);
    
    // Action buttons panel
    createActionButtonsPanel(UI_STATE.mainDialog);
    
    // Results panel
    createResultsPanel(UI_STATE.mainDialog);
    
    // Set up progress callback
    QUERY_CONFIG.runtime.progressCallback = updateUIProgress;
    
    return UI_STATE.mainDialog;
}

// FILE PATH PANEL - Document and output path selection
function createFilePathPanel(parent) {
    var filePanel = parent.add("panel", undefined, "Input/Output Configuration");
    filePanel.orientation = "column";
    filePanel.alignChildren = "fill";
    filePanel.preferredSize.height = 80;
    
    // Document path row
    var docRow = filePanel.add("group");
    docRow.add("statictext", undefined, "Document Path:");
    var docPathText = docRow.add("edittext", undefined, "");
    docPathText.preferredSize.width = 300;
    var docBrowseBtn = docRow.add("button", undefined, "Browse...");
    var loadDocBtn = docRow.add("button", undefined, "Load Doc");
    var currentDocBtn = docRow.add("button", undefined, "Current Doc");
    
    // Output path row
    var outRow = filePanel.add("group");
    outRow.add("statictext", undefined, "Output Path:");
    var outPathText = outRow.add("edittext", undefined, "");
    outPathText.preferredSize.width = 300;
    var outBrowseBtn = outRow.add("button", undefined, "Browse...");
    var openFolderBtn = outRow.add("button", undefined, "Open Folder");
    
    // Store references
    UI_STATE.configControls.docPathText = docPathText;
    UI_STATE.configControls.outPathText = outPathText;
    
    // Event handlers
    docBrowseBtn.onClick = function() {
        var file = File.openDialog("Select InDesign Document", "*.indd;*.indt");
        if (file) {
            docPathText.text = file.fsName;
            QUERY_CONFIG.paths.documentPath = file.fsName;
        }
    };
    
    currentDocBtn.onClick = function() {
        if (app.documents.length > 0) {
            var doc = app.activeDocument;
            var docPath = doc.filePath ? doc.filePath.toString() : "";
            docPathText.text = docPath;
            QUERY_CONFIG.paths.documentPath = docPath;
            QUERY_CONFIG.paths.currentDocument = doc;
        } else {
            alert("No document is currently open.");
        }
    };
    
    loadDocBtn.onClick = function() {
        if (docPathText.text) {
            try {
                var file = File(docPathText.text);
                if (file.exists) {
                    var doc = app.open(file);
                    QUERY_CONFIG.paths.currentDocument = doc;
                    updateStatus("Document loaded: " + doc.name);
                } else {
                    alert("File does not exist: " + docPathText.text);
                }
            } catch (e) {
                alert("Failed to load document: " + e.message);
            }
        }
    };
    
    outBrowseBtn.onClick = function() {
        var folder = Folder.selectDialog("Select Output Folder");
        if (folder) {
            outPathText.text = folder.fsName;
            QUERY_CONFIG.paths.outputPath = folder.fsName;
        }
    };
    
    openFolderBtn.onClick = function() {
        if (outPathText.text) {
            var folder = Folder(outPathText.text);
            if (folder.exists) {
                folder.execute();
            }
        }
    };
}

// TARGET SELECTION PANEL - Checkboxes for analysis targets
function createTargetSelectionPanel(parent) {
    var targetPanel = parent.add("panel", undefined, "Analysis Target Selection");
    targetPanel.orientation = "column";
    targetPanel.alignChildren = "fill";
    targetPanel.preferredSize.height = 100;
    
    // Create checkbox grid
    var row1 = targetPanel.add("group");
    var row2 = targetPanel.add("group");
    
    // Define target layout
    var targetList = [
        { name: "documentProperties", label: "Document Properties", row: 1 },
        { name: "pages", label: "Pages", row: 1 },
        { name: "textFrames", label: "Text Frames", row: 1 },
        { name: "stories", label: "Stories", row: 1 },
        { name: "layers", label: "Layers", row: 2 },
        { name: "images", label: "Images", row: 2 },
        { name: "links", label: "Links", row: 2 },
        { name: "pageItems", label: "Page Items", row: 2 },
        { name: "styles", label: "Styles", row: 1 },
        { name: "colors", label: "Colors", row: 1 },
        { name: "fonts", label: "Fonts", row: 1 },
        { name: "masterPages", label: "Master Pages", row: 2 }
    ];
    
    for (var i = 0; i < targetList.length; i++) {
        var target = targetList[i];
        var parentRow = target.row === 1 ? row1 : row2;
        
        var checkbox = parentRow.add("checkbox", undefined, target.label);
        checkbox.value = QUERY_CONFIG.targets[target.name].enabled;
        
        // Add safety indicator
        if (!QUERY_CONFIG.targets[target.name].safe) {
            checkbox.text += " ⚠";
            checkbox.helpTip = "Warning: This collection may be slow or cause timeouts";
        }
        
        UI_STATE.targetCheckboxes[target.name] = checkbox;
        
        // Create closure for event handler
        (function(targetName) {
            checkbox.onClick = function() {
                QUERY_CONFIG.targets[targetName].enabled = this.value;
                updateStatus("Target " + targetName + " " + (this.value ? "enabled" : "disabled"));
            };
        })(target.name);
    }
}

// CONFIGURATION PANEL - Depth, timeouts, and options
function createConfigurationPanel(parent) {
    var configPanel = parent.add("panel", undefined, "Depth & Safety Configuration");
    configPanel.orientation = "column";
    configPanel.alignChildren = "fill";
    configPanel.preferredSize.height = 80;
    
    // First row - depth and timeout
    var row1 = configPanel.add("group");
    
    row1.add("statictext", undefined, "Traversal Depth:");
    var depthSlider = row1.add("slider", undefined, QUERY_CONFIG.traversal.maxDepth, 1, 5);
    depthSlider.preferredSize.width = 100;
    var depthText = row1.add("statictext", undefined, QUERY_CONFIG.traversal.maxDepth.toString());
    
    row1.add("statictext", undefined, "   Timeout:");
    var timeoutDropdown = row1.add("dropdownlist", undefined, ["100ms", "200ms", "500ms", "1000ms", "2000ms"]);
    timeoutDropdown.selection = 2; // 500ms default
    
    row1.add("statictext", undefined, "   Sample Limit:");
    var sampleDropdown = row1.add("dropdownlist", undefined, ["5", "10", "15", "20", "25"]);
    sampleDropdown.selection = 1; // 10 default
    
    // Second row - display options
    var row2 = configPanel.add("group");
    
    var showEmptyCheck = row2.add("checkbox", undefined, "Show Empty Values");
    showEmptyCheck.value = QUERY_CONFIG.traversal.showEmpty;
    
    var showNullCheck = row2.add("checkbox", undefined, "Show Null Properties");
    showNullCheck.value = QUERY_CONFIG.traversal.showNull;
    
    var showBrokenCheck = row2.add("checkbox", undefined, "Show Broken References");
    showBrokenCheck.value = QUERY_CONFIG.traversal.showBroken;
    
    var verboseCheck = row2.add("checkbox", undefined, "Verbose Progress");
    verboseCheck.value = QUERY_CONFIG.traversal.verboseProgress;
    
    var pathTrackCheck = row2.add("checkbox", undefined, "Path Tracking");
    pathTrackCheck.value = QUERY_CONFIG.traversal.pathTracking;
    
    var bailoutCheck = row2.add("checkbox", undefined, "Emergency Bailouts");
    bailoutCheck.value = QUERY_CONFIG.traversal.emergencyBailouts;
    
    // Store references
    UI_STATE.configControls.depthSlider = depthSlider;
    UI_STATE.configControls.timeoutDropdown = timeoutDropdown;
    UI_STATE.configControls.sampleDropdown = sampleDropdown;
    
    // Event handlers
    depthSlider.onChanging = function() {
        var depth = Math.round(this.value);
        depthText.text = depth.toString();
        QUERY_CONFIG.traversal.maxDepth = depth;
    };
    
    timeoutDropdown.onChange = function() {
        var timeouts = [100, 200, 500, 1000, 2000];
        QUERY_CONFIG.traversal.timeoutMs = timeouts[this.selection.index];
    };
    
    sampleDropdown.onChange = function() {
        var limits = [5, 10, 15, 20, 25];
        QUERY_CONFIG.traversal.sampleLimit = limits[this.selection.index];
    };
    
    showEmptyCheck.onClick = function() {
        QUERY_CONFIG.traversal.showEmpty = this.value;
    };
    
    showNullCheck.onClick = function() {
        QUERY_CONFIG.traversal.showNull = this.value;
    };
    
    showBrokenCheck.onClick = function() {
        QUERY_CONFIG.traversal.showBroken = this.value;
    };
    
    verboseCheck.onClick = function() {
        QUERY_CONFIG.traversal.verboseProgress = this.value;
    };
    
    pathTrackCheck.onClick = function() {
        QUERY_CONFIG.traversal.pathTracking = this.value;
    };
    
    bailoutCheck.onClick = function() {
        QUERY_CONFIG.traversal.emergencyBailouts = this.value;
    };
}

// PROGRESS PANEL - Real-time progress feedback
function createProgressPanel(parent) {
    var progressPanel = parent.add("panel", undefined, "Analysis Progress");
    progressPanel.orientation = "column";
    progressPanel.alignChildren = "fill";
    progressPanel.preferredSize.height = 120;
    
    // Status and progress bar
    var statusRow = progressPanel.add("group");
    statusRow.add("statictext", undefined, "Status:");
    UI_STATE.statusText = statusRow.add("statictext", undefined, "Ready");
    UI_STATE.statusText.preferredSize.width = 300;
    
    UI_STATE.progressBar = statusRow.add("progressbar", undefined, 0, 100);
    UI_STATE.progressBar.preferredSize.width = 200;
    
    var percentText = statusRow.add("statictext", undefined, "0%");
    UI_STATE.configControls.percentText = percentText;
    
    // Current operation details
    var currentRow = progressPanel.add("group");
    currentRow.add("statictext", undefined, "Current:");
    UI_STATE.progressText = currentRow.add("statictext", undefined, "");
    UI_STATE.progressText.preferredSize.width = 600;
    
    // Path tracking (scrollable)
    var pathGroup = progressPanel.add("group");
    pathGroup.orientation = "column";
    pathGroup.alignChildren = "fill";
    
    var pathLabel = pathGroup.add("statictext", undefined, "Recent Paths:");
    UI_STATE.pathList = pathGroup.add("edittext", undefined, "", {multiline: true, readonly: true});
    UI_STATE.pathList.preferredSize.height = 40;
}

// ACTION BUTTONS PANEL - Presets and controls
function createActionButtonsPanel(parent) {
    var actionPanel = parent.add("group");
    actionPanel.orientation = "row";
    actionPanel.alignChildren = "center";
    
    // Presets group
    var presetsGroup = actionPanel.add("panel", undefined, "Quick Actions");
    presetsGroup.orientation = "row";
    
    var basicBtn = presetsGroup.add("button", undefined, "Preset: Basic Safe");
    var textBtn = presetsGroup.add("button", undefined, "Preset: Text Only");
    var fullBtn = presetsGroup.add("button", undefined, "Preset: Full Scan");
    var saveConfigBtn = presetsGroup.add("button", undefined, "Save Config");
    
    // Analysis controls group
    var controlsGroup = actionPanel.add("panel", undefined, "Analysis Control");
    controlsGroup.orientation = "row";
    
    var startBtn = controlsGroup.add("button", undefined, "▶ START ANALYSIS");
    startBtn.preferredSize.width = 140;
    var pauseBtn = controlsGroup.add("button", undefined, "⏸ PAUSE");
    var stopBtn = controlsGroup.add("button", undefined, "⏹ STOP");
    var viewBtn = controlsGroup.add("button", undefined, "📊 View Results");
    var exportBtn = controlsGroup.add("button", undefined, "📁 Export Tree");
    
    // Store references
    UI_STATE.configControls.startBtn = startBtn;
    UI_STATE.configControls.pauseBtn = pauseBtn;
    UI_STATE.configControls.stopBtn = stopBtn;
    
    // Event handlers
    basicBtn.onClick = function() {
        applyPreset("basicSafe");
        refreshTargetCheckboxes();
        updateStatus("Applied Basic Safe preset");
    };
    
    textBtn.onClick = function() {
        applyPreset("textOnly");
        refreshTargetCheckboxes();
        updateStatus("Applied Text Only preset");
    };
    
    fullBtn.onClick = function() {
        applyPreset("fullScan");
        refreshTargetCheckboxes();
        updateStatus("Applied Full Scan preset");
    };
    
    startBtn.onClick = function() {
        startAnalysis();
    };
    
    viewBtn.onClick = function() {
        if (UI_STATE.currentResults) {
            showResultsDialog(UI_STATE.currentResults);
        } else {
            alert("No results to display. Run an analysis first.");
        }
    };
    
    exportBtn.onClick = function() {
        if (UI_STATE.currentResults) {
            exportTreeToFile(UI_STATE.currentResults);
        } else {
            alert("No results to export. Run an analysis first.");
        }
    };
}

// RESULTS PANEL - Tree display area
function createResultsPanel(parent) {
    var resultsPanel = parent.add("panel", undefined, "Quick Results Preview");
    resultsPanel.orientation = "column";
    resultsPanel.alignChildren = "fill";
    resultsPanel.preferredSize.height = 150;
    
    UI_STATE.resultTree = resultsPanel.add("edittext", undefined, "No analysis results yet...", {multiline: true, readonly: true});
    UI_STATE.resultTree.alignment = "fill";
}

// UI UPDATE FUNCTIONS
function updateUIProgress(progress) {
    if (!UI_STATE.mainDialog) return;
    
    try {
        if (UI_STATE.statusText) {
            UI_STATE.statusText.text = progress.status + " - " + progress.currentTarget;
        }
        
        if (UI_STATE.progressBar) {
            UI_STATE.progressBar.value = progress.percentage || 0;
        }
        
        if (UI_STATE.configControls.percentText) {
            UI_STATE.configControls.percentText.text = (progress.percentage || 0) + "%";
        }
        
        if (UI_STATE.progressText) {
            UI_STATE.progressText.text = progress.currentPath + " → " + progress.currentResult;
        }
        
        // Add to path list if verbose
        if (QUERY_CONFIG.traversal.verboseProgress && UI_STATE.pathList) {
            var pathEntry = progress.currentPath + " → " + progress.currentResult + "\n";
            var currentText = UI_STATE.pathList.text;
            var lines = currentText.split("\n");
            if (lines.length > 10) {
                lines = lines.slice(-8); // Keep last 8 lines
            }
            lines.push(pathEntry);
            UI_STATE.pathList.text = lines.join("\n");
        }
        
        UI_STATE.mainDialog.update();
        
    } catch (e) {
        // Ignore UI update errors
    }
}

function updateStatus(message) {
    if (UI_STATE.statusText) {
        UI_STATE.statusText.text = message;
        UI_STATE.mainDialog.update();
    }
    $.writeln("[UI] " + message);
}

function refreshTargetCheckboxes() {
    for (var targetName in UI_STATE.targetCheckboxes) {
        var checkbox = UI_STATE.targetCheckboxes[targetName];
        if (checkbox) {
            checkbox.value = QUERY_CONFIG.targets[targetName].enabled;
        }
    }
}

// ANALYSIS CONTROL
function startAnalysis() {
    if (isAnalysisActive()) {
        alert("Analysis is already running.");
        return;
    }
    
    var doc = QUERY_CONFIG.paths.currentDocument;
    if (!doc && app.documents.length > 0) {
        doc = app.activeDocument;
        QUERY_CONFIG.paths.currentDocument = doc;
    }
    
    if (!doc) {
        alert("No document available for analysis. Please load or select a document.");
        return;
    }
    
    updateStatus("Starting analysis...");
    
    try {
        var results = analyzeDocumentToTree(doc);
        UI_STATE.currentResults = results;
        
        if (results) {
            var stats = getTreeStatistics(results);
            var summary = "Analysis Complete!\n" +
                         "Total nodes: " + stats.totalNodes + "\n" +
                         "Success: " + stats.successNodes + "\n" +
                         "Errors: " + stats.errorNodes + "\n" +
                         "Max depth: " + stats.maxDepth;
            
            UI_STATE.resultTree.text = summary;
            updateStatus("Analysis completed successfully");
        } else {
            updateStatus("Analysis failed - no results");
        }
        
    } catch (e) {
        updateStatus("Analysis failed: " + e.message);
        alert("Analysis failed: " + e.message);
    }
}

// SHOW MAIN INTERFACE
function showMainInterface() {
    var dialog = createMainInterface();
    
    // Set initial document if available
    if (app.documents.length > 0) {
        var doc = app.activeDocument;
        QUERY_CONFIG.paths.currentDocument = doc;
        if (doc.saved && doc.filePath) {
            UI_STATE.configControls.docPathText.text = doc.filePath.toString();
            QUERY_CONFIG.paths.documentPath = doc.filePath.toString();
        }
    }
    
    dialog.show();
}

$.writeln("Module C: UI Panel & Controls loaded");

// ==============================================================================
// MODULE 4 (v4.0): MODULE_4.0_EXPORTANDRESULTSDISPLAY.JSX
// ==============================================================================

verifyModuleLoad("Module_4.0_ExportAndResultsDisplay");

// ============================================================================
// MODULE 4.0: EXPORT & RESULTS DISPLAY
// InDesign Document Query Tool v3.0 - Configurable Analysis
// ES3 Compatible - Tree Export and Results Viewer
// ============================================================================

// RESULTS DISPLAY DIALOG - Expandable tree view
function showResultsDialog(treeResults) {
    if (!treeResults) {
        alert("No results to display.");
        return;
    }
    
    var resultsDialog = new Window("dialog", "Analysis Results - DOM Tree View");
    resultsDialog.orientation = "column";
    resultsDialog.alignChildren = "fill";
    resultsDialog.preferredSize.width = 800;
    resultsDialog.preferredSize.height = 600;
    
    // Header with statistics
    var headerPanel = resultsDialog.add("panel", undefined, "Results Summary");
    headerPanel.orientation = "row";
    headerPanel.alignChildren = "center";
    
    var stats = getTreeStatistics(treeResults);
    var statsText = "Total Nodes: " + stats.totalNodes + 
                   " | Success: " + stats.successNodes + 
                   " | Errors: " + stats.errorNodes + 
                   " | Null: " + stats.nullNodes + 
                   " | Empty: " + stats.emptyNodes + 
                   " | Max Depth: " + stats.maxDepth;
    
    headerPanel.add("statictext", undefined, statsText);
    
    // Tree display area
    var treePanel = resultsDialog.add("panel", undefined, "Document Tree");
    treePanel.orientation = "column";
    treePanel.alignChildren = "fill";
    
    var treeText = treePanel.add("edittext", undefined, "", {multiline: true, readonly: true});
    treeText.alignment = "fill";
    
    // Convert tree to display format
    var treeDisplay = formatTreeForDisplay(treeResults, 0, true);
    treeText.text = treeDisplay;
    
    // Controls
    var controlsPanel = resultsDialog.add("group");
    controlsPanel.orientation = "row";
    controlsPanel.alignment = "center";
    
    var expandBtn = controlsPanel.add("button", undefined, "Expand All");
    var collapseBtn = controlsPanel.add("button", undefined, "Collapse All");
    var exportBtn = controlsPanel.add("button", undefined, "Export to File");
    var copyBtn = controlsPanel.add("button", undefined, "Copy to Clipboard");
    var closeBtn = controlsPanel.add("button", undefined, "Close");
    
    // Event handlers
    expandBtn.onClick = function() {
        var expandedDisplay = formatTreeForDisplay(treeResults, 0, true, true);
        treeText.text = expandedDisplay;
    };
    
    collapseBtn.onClick = function() {
        var collapsedDisplay = formatTreeForDisplay(treeResults, 0, false, false);
        treeText.text = collapsedDisplay;
    };
    
    exportBtn.onClick = function() {
        exportTreeToFile(treeResults);
    };
    
    copyBtn.onClick = function() {
        copyTreeToClipboard(treeResults);
    };
    
    closeBtn.onClick = function() {
        resultsDialog.close();
    };
    
    resultsDialog.show();
}

// FORMAT TREE FOR DISPLAY - Convert tree to readable text format
function formatTreeForDisplay(node, depth, showChildren, expandAll) {
    if (!node) return "";
    
    var output = "";
    var indent = "";
    
    // Create indentation
    for (var i = 0; i < depth; i++) {
        indent += "  ";
    }
    
    // Format current node
    var nodeSymbol = getDisplaySymbol(node.status);
    var nodeDisplay = indent + nodeSymbol + " " + node.name;
    
    // Add type and value info
    if (node.type && node.type !== "unknown") {
        nodeDisplay += " (" + node.type + ")";
    }
    
    if (node.value && node.value !== node.name) {
        var valueDisplay = String(node.value);
        if (valueDisplay.length > 60) {
            valueDisplay = valueDisplay.substring(0, 60) + "...";
        }
        nodeDisplay += ": " + valueDisplay;
    }
    
    // Add path for debugging
    if (QUERY_CONFIG.traversal.pathTracking && node.path) {
        nodeDisplay += " [" + node.path + "]";
    }
    
    output += nodeDisplay + "\n";
    
    // Add children if requested
    if (showChildren && node.children && node.children.length > 0) {
        var shouldShowChildren = expandAll || depth < 2; // Auto-expand first 2 levels
        
        if (shouldShowChildren) {
            for (var i = 0; i < node.children.length; i++) {
                output += formatTreeForDisplay(node.children[i], depth + 1, true, expandAll);
            }
        } else {
            output += indent + "  [...] " + node.children.length + " children (click Expand All to show)\n";
        }
    }
    
    return output;
}

function getDisplaySymbol(status) {
    var symbols = {
        success: "✓",
        error: "✗",
        timeout: "⏱",
        null: "∅",
        empty: "○",
        skipped: "⏭",
        disabled: "⏸",
        truncated: "…",
        unknown: "?"
    };
    
    return symbols[status] || "?";
}

// EXPORT TREE TO FILE - Save complete tree structure
function exportTreeToFile(treeResults) {
    if (!treeResults) {
        alert("No results to export.");
        return;
    }
    
    var outputPath = QUERY_CONFIG.paths.outputPath;
    if (!outputPath) {
        var folder = Folder.selectDialog("Select folder to save tree export");
        if (!folder) return;
        outputPath = folder.fsName;
        QUERY_CONFIG.paths.outputPath = outputPath;
    }
    
    try {
        var timestamp = new Date();
        var dateStr = timestamp.getFullYear() + 
                     pad(timestamp.getMonth() + 1) + 
                     pad(timestamp.getDate()) + "_" + 
                     pad(timestamp.getHours()) + 
                     pad(timestamp.getMinutes()) + 
                     pad(timestamp.getSeconds());
        
        var filename = "InDesign_QueryResults_" + dateStr + ".txt";
        var filepath = outputPath + "/" + filename;
        var file = File(filepath);
        
        file.open("w");
        
        // Write header
        file.writeln("InDesign Document Query Tool v3.0 - Analysis Results");
        file.writeln("Generated: " + timestamp.toString());
        file.writeln("Document: " + (QUERY_CONFIG.paths.documentPath || "Unknown"));
        file.writeln("Analysis Configuration:");
        file.writeln("  Traversal Depth: " + QUERY_CONFIG.traversal.maxDepth);
        file.writeln("  Sample Limit: " + QUERY_CONFIG.traversal.sampleLimit);
        file.writeln("  Timeout: " + QUERY_CONFIG.traversal.timeoutMs + "ms");
        file.writeln("  Show Empty: " + QUERY_CONFIG.traversal.showEmpty);
        file.writeln("  Show Null: " + QUERY_CONFIG.traversal.showNull);
        file.writeln("  Emergency Bailouts: " + QUERY_CONFIG.traversal.emergencyBailouts);
        
        // Write enabled targets
        file.writeln("Enabled Targets:");
        var enabledTargets = getEnabledTargets();
        for (var i = 0; i < enabledTargets.length; i++) {
            file.writeln("  - " + enabledTargets[i]);
        }
        file.writeln("");
        
        // Write statistics
        var stats = getTreeStatistics(treeResults);
        file.writeln("ANALYSIS STATISTICS:");
        file.writeln("  Total Nodes: " + stats.totalNodes);
        file.writeln("  Success Nodes: " + stats.successNodes);
        file.writeln("  Error Nodes: " + stats.errorNodes);
        file.writeln("  Null Nodes: " + stats.nullNodes);
        file.writeln("  Empty Nodes: " + stats.emptyNodes);
        file.writeln("  Timeout Nodes: " + stats.timeoutNodes);
        file.writeln("  Maximum Depth Reached: " + stats.maxDepth);
        file.writeln("");
        
        // Write tree structure
        file.writeln("DOCUMENT TREE STRUCTURE:");
        file.writeln("========================");
        file.writeln("");
        
        var treeText = formatTreeForExport(treeResults, 0);
        file.write(treeText);
        
        // Write JSON export
        file.writeln("");
        file.writeln("JSON EXPORT (for programmatic use):");
        file.writeln("===================================");
        try {
            var jsonExport = createJSONExport(treeResults);
            file.write(JSON.stringify(jsonExport, null, 2));
        } catch (jsonError) {
            file.writeln("JSON export failed: " + jsonError.message);
        }
        
        file.close();
        
        alert("Results exported successfully to:\n" + filepath);
        
    } catch (e) {
        alert("Export failed: " + e.message);
    }
}

// FORMAT TREE FOR EXPORT - Complete tree with all details
function formatTreeForExport(node, depth) {
    if (!node) return "";
    
    var output = "";
    var indent = "";
    
    // Create indentation
    for (var i = 0; i < depth; i++) {
        indent += "  ";
    }
    
    // Format node with complete information
    output += indent + "├─ " + node.name + "\n";
    output += indent + "│  Type: " + (node.type || "unknown") + "\n";
    output += indent + "│  Status: " + (node.status || "unknown") + "\n";
    
    if (node.value !== undefined && node.value !== null) {
        var valueStr = String(node.value);
        if (valueStr.length > 200) {
            valueStr = valueStr.substring(0, 200) + "... [truncated]";
        }
        output += indent + "│  Value: " + valueStr + "\n";
    }
    
    if (node.path) {
        output += indent + "│  Path: " + node.path + "\n";
    }
    
    output += indent + "│\n";
    
    // Add children
    if (node.children && node.children.length > 0) {
        for (var i = 0; i < node.children.length; i++) {
            output += formatTreeForExport(node.children[i], depth + 1);
        }
    }
    
    return output;
}

// CREATE JSON EXPORT - Structured data for programmatic use
function createJSONExport(treeResults) {
    var export_data = {
        metadata: {
            version: QUERY_CONFIG.version,
            timestamp: new Date().toISOString ? new Date().toISOString() : new Date().toString(),
            document: QUERY_CONFIG.paths.documentPath || "unknown",
            configuration: {
                maxDepth: QUERY_CONFIG.traversal.maxDepth,
                sampleLimit: QUERY_CONFIG.traversal.sampleLimit,
                timeoutMs: QUERY_CONFIG.traversal.timeoutMs,
                showEmpty: QUERY_CONFIG.traversal.showEmpty,
                showNull: QUERY_CONFIG.traversal.showNull,
                emergencyBailouts: QUERY_CONFIG.traversal.emergencyBailouts
            },
            enabledTargets: getEnabledTargets(),
            statistics: getTreeStatistics(treeResults)
        },
        tree: convertTreeToJSON(treeResults)
    };
    
    return export_data;
}

function convertTreeToJSON(node) {
    if (!node) return null;
    
    var jsonNode = {
        name: node.name,
        type: node.type,
        status: node.status,
        path: node.path
    };
    
    // Only include value if it's meaningful
    if (node.value !== undefined && node.value !== null && node.value !== node.name) {
        jsonNode.value = node.value;
    }
    
    // Include children if present
    if (node.children && node.children.length > 0) {
        jsonNode.children = [];
        for (var i = 0; i < node.children.length; i++) {
            var childJSON = convertTreeToJSON(node.children[i]);
            if (childJSON) {
                jsonNode.children.push(childJSON);
            }
        }
    }
    
    return jsonNode;
}

// COPY TO CLIPBOARD - Simple text copy
function copyTreeToClipboard(treeResults) {
    if (!treeResults) {
        alert("No results to copy.");
        return;
    }
    
    try {
        var treeText = formatTreeForDisplay(treeResults, 0, true, true);
        
        // Create temporary text file for clipboard
        var tempFile = File(Folder.temp + "/indesign_query_temp.txt");
        tempFile.open("w");
        tempFile.write(treeText);
        tempFile.close();
        
        alert("Tree structure has been prepared for copying.\nTemporary file created at: " + tempFile.fsName + "\n\nOpen this file and copy its contents to your clipboard.");
        
        // Try to open the file
        tempFile.execute();
        
    } catch (e) {
        alert("Copy to clipboard failed: " + e.message);
    }
}

// COMPARISON UTILITIES - For comparing two tree results
function compareTreeResults(tree1, tree2) {
    var comparison = {
        timestamp: new Date().toString(),
        tree1Stats: getTreeStatistics(tree1),
        tree2Stats: getTreeStatistics(tree2),
        differences: [],
        summary: {
            nodeCountChanged: false,
            structureChanged: false,
            valuesChanged: false
        }
    };
    
    // Basic statistical comparison
    if (comparison.tree1Stats.totalNodes !== comparison.tree2Stats.totalNodes) {
        comparison.summary.nodeCountChanged = true;
        comparison.differences.push({
            type: "node_count_change",
            from: comparison.tree1Stats.totalNodes,
            to: comparison.tree2Stats.totalNodes
        });
    }
    
    // Deep comparison would go here
    // For now, just provide structure for future implementation
    comparison.differences.push({
        type: "info",
        message: "Deep tree comparison not yet implemented. Use manual comparison of exported files."
    });
    
    return comparison;
}

// UTILITY FUNCTIONS
function pad(number) {
    return number < 10 ? "0" + number : number.toString();
}

function createResultsSummary(treeResults) {
    if (!treeResults) return "No results available";
    
    var stats = getTreeStatistics(treeResults);
    var summary = "ANALYSIS SUMMARY\n";
    summary += "================\n\n";
    summary += "Total Nodes Analyzed: " + stats.totalNodes + "\n";
    summary += "Successful Accesses: " + stats.successNodes + "\n";
    summary += "Errors Encountered: " + stats.errorNodes + "\n";
    summary += "Null Values Found: " + stats.nullNodes + "\n";
    summary += "Empty Values Found: " + stats.emptyNodes + "\n";
    summary += "Timeouts Occurred: " + stats.timeoutNodes + "\n";
    summary += "Maximum Depth Reached: " + stats.maxDepth + "\n\n";
    
    var successRate = stats.totalNodes > 0 ? Math.round((stats.successNodes / stats.totalNodes) * 100) : 0;
    summary += "Success Rate: " + successRate + "%\n\n";
    
    // Analysis recommendations
    summary += "RECOMMENDATIONS:\n";
    if (stats.errorNodes > stats.successNodes) {
        summary += "• High error rate detected - consider using emergency bailouts\n";
        summary += "• Try reducing traversal depth or sample limits\n";
    } else if (stats.timeoutNodes > 5) {
        summary += "• Multiple timeouts detected - consider increasing timeout values\n";
        summary += "• Some collections may be slow - disable risky collections\n";
    } else if (successRate > 90) {
        summary += "• Excellent success rate - document is healthy for analysis\n";
        summary += "• Consider enabling more targets for deeper analysis\n";
    }
    
    if (stats.maxDepth < QUERY_CONFIG.traversal.maxDepth) {
        summary += "• Analysis stopped before reaching maximum depth\n";
        summary += "• Consider increasing timeout or reducing sample size\n";
    }
    
    return summary;
}

// EXPORT CONFIGURATION - Save current settings
function exportConfiguration() {
    var configExport = {
        version: QUERY_CONFIG.version,
        timestamp: new Date().toString(),
        targets: {},
        traversal: QUERY_CONFIG.traversal
    };
    
    // Export enabled targets
    for (var target in QUERY_CONFIG.targets) {
        configExport.targets[target] = QUERY_CONFIG.targets[target].enabled;
    }
    
    try {
        var configFile = File.saveDialog("Save Query Configuration", "*.json");
        if (configFile) {
            configFile.open("w");
            configFile.write(JSON.stringify(configExport, null, 2));
            configFile.close();
            alert("Configuration saved to: " + configFile.name);
        }
    } catch (e) {
        alert("Failed to save configuration: " + e.message);
    }
}

// IMPORT CONFIGURATION - Load saved settings
function importConfiguration() {
    try {
        var configFile = File.openDialog("Load Query Configuration", "*.json");
        if (configFile) {
            configFile.open("r");
            var configData = configFile.read();
            configFile.close();
            
            var config = JSON.parse(configData);
            
            // Apply loaded configuration
            if (config.targets) {
                for (var target in config.targets) {
                    if (QUERY_CONFIG.targets[target]) {
                        QUERY_CONFIG.targets[target].enabled = config.targets[target];
                    }
                }
            }
            
            if (config.traversal) {
                QUERY_CONFIG.traversal.maxDepth = config.traversal.maxDepth || QUERY_CONFIG.traversal.maxDepth;
                QUERY_CONFIG.traversal.sampleLimit = config.traversal.sampleLimit || QUERY_CONFIG.traversal.sampleLimit;
                QUERY_CONFIG.traversal.timeoutMs = config.traversal.timeoutMs || QUERY_CONFIG.traversal.timeoutMs;
                QUERY_CONFIG.traversal.showEmpty = config.traversal.showEmpty !== undefined ? config.traversal.showEmpty : QUERY_CONFIG.traversal.showEmpty;
                QUERY_CONFIG.traversal.showNull = config.traversal.showNull !== undefined ? config.traversal.showNull : QUERY_CONFIG.traversal.showNull;
            }
            
            alert("Configuration loaded successfully!");
            return true;
        }
    } catch (e) {
        alert("Failed to load configuration: " + e.message);
    }
    
    return false;
}

$.writeln("Module D: Export & Results Display loaded");

// ==============================================================================
// MODULE 5 (v5.0): MODULE_5.0_MAINENTRYPOINT.JSX
// ==============================================================================

verifyModuleLoad("Module_5.0_MainEntryPoint");

// ============================================================================
// MODULE 5.0: MAIN ENTRY POINT
// InDesign Document Query Tool v3.0 - Configurable Analysis
// ES3 Compatible - Script Initialization and Startup
// ============================================================================

// MAIN INITIALIZATION - Entry point for the entire tool
function initializeQueryTool() {
    try {
        $.writeln("=".repeat ? "=".repeat(60) : "============================================================");
        $.writeln("InDesign Document Query Tool v3.0 - Configurable Analysis");
        $.writeln("Lightweight DOM Tree Generator with Progressive Safety");
        $.writeln("Loading modular architecture...");
        $.writeln("=".repeat ? "=".repeat(60) : "============================================================");
        
        // Verify all modules are loaded
        var moduleTests = [
            { name: "Module A (Config)", test: function() { return typeof QUERY_CONFIG !== 'undefined'; } },
            { name: "Module B (Analysis)", test: function() { return typeof analyzeDocumentToTree === 'function'; } },
            { name: "Module C (UI)", test: function() { return typeof createMainInterface === 'function'; } },
            { name: "Module D (Export)", test: function() { return typeof showResultsDialog === 'function'; } }
        ];
        
        $.writeln("Module verification:");
        for (var i = 0; i < moduleTests.length; i++) {
            var module = moduleTests[i];
            var passed = module.test();
            $.writeln("  " + module.name + ": " + (passed ? "✓ LOADED" : "✗ MISSING"));
            if (!passed) {
                throw new Error(module.name + " failed to load properly");
            }
        }
        
        $.writeln("\nAll modules loaded successfully!");
        $.writeln("Initializing query tool interface...");
        
        // Show startup dialog
        showStartupDialog();
        
    } catch (exc) {
        var errorMsg = "InDesign Document Query Tool v3.0\n\n" +
                       "Initialization Error: " + exc.message + "\n\n" +
                       "This tool requires all modules to be loaded properly.\n" +
                       "Please ensure all module files are available.";
        
        alert(errorMsg);
        $.writeln("INITIALIZATION ERROR: " + exc.message);
    }
}

// STARTUP DIALOG - Choose how to launch the tool
function showStartupDialog() {
    var startupDialog = new Window("dialog", "InDesign Document Query Tool v3.0");
    startupDialog.orientation = "column";
    startupDialog.alignChildren = "fill";
    startupDialog.preferredSize.width = 500;
    startupDialog.preferredSize.height = 400;
    
    // Header
    var headerPanel = startupDialog.add("panel", undefined, "Welcome to Document Query Tool v3.0");
    headerPanel.orientation = "column";
    headerPanel.alignChildren = "fill";
    
    var welcomeText = headerPanel.add("statictext", undefined, 
        "A lightweight, configurable tool for analyzing InDesign documents.\n" +
        "Generate DOM-like trees of document properties with safety controls.\n\n" +
        "✓ Progressive safety system prevents hanging\n" +
        "✓ Configurable analysis targets and depth\n" +
        "✓ Real-time progress tracking\n" +
        "✓ Export results to files or view in tree format",
        {multiline: true});
    welcomeText.alignment = "fill";
    
    // Document status
    var statusPanel = startupDialog.add("panel", undefined, "Current Document Status");
    statusPanel.orientation = "column";
    statusPanel.alignChildren = "fill";
    
    var docStatus = "No document open";
    var canAnalyze = false;
    
    if (app.documents.length > 0) {
        var doc = app.activeDocument;
        var docName = "Unknown";
        try {
            docName = doc.name || "Unnamed Document";
            docStatus = "Document: " + docName;
            if (doc.saved && doc.filePath) {
                docStatus += "\nPath: " + doc.filePath.toString();
                docStatus += "\nStatus: Saved and ready for analysis";
                canAnalyze = true;
            } else {
                docStatus += "\nStatus: Unsaved (can still analyze)";
                canAnalyze = true;
            }
        } catch (e) {
            docStatus = "Document access error: " + e.message;
        }
    }
    
    var docStatusText = statusPanel.add("statictext", undefined, docStatus, {multiline: true});
    docStatusText.alignment = "fill";
    
    // Quick start options
    var quickPanel = startupDialog.add("panel", undefined, "Quick Start Options");
    quickPanel.orientation = "column";
    quickPanel.alignChildren = "fill";
    
    var fullInterfaceBtn = quickPanel.add("button", undefined, "🎛️ Open Full Interface (Recommended)");
    fullInterfaceBtn.preferredSize.height = 35;
    
    var quickAnalysisBtn = quickPanel.add("button", undefined, "⚡ Quick Analysis (Current Document)");
    quickAnalysisBtn.preferredSize.height = 35;
    quickAnalysisBtn.enabled = canAnalyze;
    
    var loadDocBtn = quickPanel.add("button", undefined, "📁 Load Document & Analyze");
    loadDocBtn.preferredSize.height = 35;
    
    // Advanced options
    var advancedPanel = startupDialog.add("panel", undefined, "Advanced Options");
    advancedPanel.orientation = "row";
    advancedPanel.alignChildren = "center";
    
    var configBtn = advancedPanel.add("button", undefined, "⚙️ Load Config");
    var helpBtn = advancedPanel.add("button", undefined, "❓ Help");
    var aboutBtn = advancedPanel.add("button", undefined, "ℹ️ About");
    
    // Bottom buttons
    var buttonPanel = startupDialog.add("group");
    buttonPanel.orientation = "row";
    buttonPanel.alignment = "center";
    
    var cancelBtn = buttonPanel.add("button", undefined, "Cancel");
    
    // Event handlers
    fullInterfaceBtn.onClick = function() {
        startupDialog.close();
        showMainInterface();
    };
    
    quickAnalysisBtn.onClick = function() {
        startupDialog.close();
        runQuickAnalysis();
    };
    
    loadDocBtn.onClick = function() {
        startupDialog.close();
        loadDocumentAndAnalyze();
    };
    
    configBtn.onClick = function() {
        if (importConfiguration()) {
            alert("Configuration loaded! The settings will be applied when you open the interface.");
        }
    };
    
    helpBtn.onClick = function() {
        showHelpDialog();
    };
    
    aboutBtn.onClick = function() {
        showAboutDialog();
    };
    
    cancelBtn.onClick = function() {
        startupDialog.close();
    };
    
    startupDialog.show();
}

// QUICK ANALYSIS - Fast analysis with default settings
function runQuickAnalysis() {
    if (app.documents.length === 0) {
        alert("No document is currently open. Please open a document first.");
        return;
    }
    
    try {
        var doc = app.activeDocument;
        
        // Apply basic safe preset
        applyPreset("basicSafe");
        
        $.writeln("Starting quick analysis with Basic Safe preset...");
        
        // Create simple progress dialog
        var progressDialog = new Window("dialog", "Quick Analysis in Progress");
        progressDialog.orientation = "column";
        progressDialog.alignChildren = "center";
        progressDialog.preferredSize.width = 400;
        
        var statusText = progressDialog.add("statictext", undefined, "Analyzing document...");
        var progressBar = progressDialog.add("progressbar", undefined, 0, 100);
        progressBar.preferredSize.width = 300;
        
        var cancelBtn = progressDialog.add("button", undefined, "Cancel");
        var cancelled = false;
        
        cancelBtn.onClick = function() {
            cancelled = true;
            progressDialog.close();
        };
        
        // Set up progress callback
        QUERY_CONFIG.runtime.progressCallback = function(progress) {
            if (cancelled) return;
            statusText.text = progress.currentTarget + ": " + progress.currentPath;
            progressBar.value = progress.percentage || 0;
            progressDialog.update();
        };
        
        progressDialog.show();
        
        if (!cancelled) {
            var results = analyzeDocumentToTree(doc);
            progressDialog.close();
            
            if (results) {
                showResultsDialog(results);
            } else {
                alert("Quick analysis failed to generate results.");
            }
        }
        
    } catch (e) {
        alert("Quick analysis failed: " + e.message);
        $.writeln("Quick analysis error: " + e.message);
    }
}

// LOAD DOCUMENT AND ANALYZE - File picker and analysis
function loadDocumentAndAnalyze() {
    try {
        var file = File.openDialog("Select InDesign Document", "*.indd;*.indt");
        if (!file) return;
        
        $.writeln("Loading document: " + file.fsName);
        
        var doc = app.open(file);
        QUERY_CONFIG.paths.currentDocument = doc;
        QUERY_CONFIG.paths.documentPath = file.fsName;
        
        alert("Document loaded: " + doc.name + "\n\nOpening analysis interface...");
        
        showMainInterface();
        
    } catch (e) {
        alert("Failed to load document: " + e.message);
        $.writeln("Document load error: " + e.message);
    }
}

// HELP DIALOG - Usage instructions
function showHelpDialog() {
    var helpDialog = new Window("dialog", "InDesign Document Query Tool - Help");
    helpDialog.orientation = "column";
    helpDialog.alignChildren = "fill";
    helpDialog.preferredSize.width = 600;
    helpDialog.preferredSize.height = 500;
    
    var helpText = helpDialog.add("edittext", undefined, 
        "INDESIGN DOCUMENT QUERY TOOL v3.0 - HELP\n" +
        "==========================================\n\n" +
        
        "OVERVIEW:\n" +
        "This tool analyzes InDesign documents and creates DOM-like trees of properties,\n" +
        "collections, and values. It's designed to be safe and prevent hanging.\n\n" +
        
        "GETTING STARTED:\n" +
        "1. Open an InDesign document (or use 'Load Document')\n" +
        "2. Choose 'Open Full Interface' for complete control\n" +
        "3. Or use 'Quick Analysis' for fast results with safe defaults\n\n" +
        
        "MAIN INTERFACE:\n" +
        "• File Paths: Set document and output locations\n" +
        "• Target Selection: Choose what to analyze (checkboxes)\n" +
        "• Configuration: Set depth, timeouts, and display options\n" +
        "• Presets: Quick configurations (Basic Safe, Text Only, Full Scan)\n" +
        "• Progress: Real-time feedback shows current operations\n\n" +
        
        "ANALYSIS TARGETS:\n" +
        "✓ Document Properties - Core document info (always safe)\n" +
        "✓ Pages - Page collection and properties (safe)\n" +
        "✓ Text Frames - Text frame objects (safe)\n" +
        "✓ Stories - Story objects and threading (safe)\n" +
        "✓ Layers - Layer information (safe)\n" +
        "⚠ Images - Image objects (can be slow, use caution)\n" +
        "⚠ Links - Link information (can be slow, use caution)\n" +
        "⚠ Page Items - All page items (can be very slow)\n" +
        "✓ Styles - Paragraph and character styles (safe)\n" +
        "✓ Colors - Color definitions (safe)\n" +
        "✓ Fonts - Font information (safe)\n\n" +
        
        "SAFETY FEATURES:\n" +
        "• Emergency Bailouts: Stop operations that take too long\n" +
        "• Progressive Depth: Limit how deep the analysis goes\n" +
        "• Sample Limits: Only analyze a subset of large collections\n" +
        "• Timeout Controls: Set maximum time for operations\n" +
        "• Real-time Progress: See exactly what's being analyzed\n\n" +
        
        "RESULTS:\n" +
        "• Tree View: Hierarchical display of document structure\n" +
        "• Export Options: Save to text files or JSON format\n" +
        "• Statistics: Success rates, error counts, depth reached\n" +
        "• Path Tracking: See exact property paths that were tested\n\n" +
        
        "PRESETS:\n" +
        "• Basic Safe: Only safest collections, depth 2, 5 samples\n" +
        "• Text Only: Focus on text-related properties\n" +
        "• Full Scan: All collections with safety limits\n\n" +
        
        "TROUBLESHOOTING:\n" +
        "• If analysis hangs: Use lower depth, smaller samples, shorter timeouts\n" +
        "• For complex documents: Start with Basic Safe preset\n" +
        "• High error rates: Enable Emergency Bailouts\n" +
        "• Slow performance: Reduce sample limits and disable risky collections\n\n" +
        
        "OUTPUT FORMATS:\n" +
        "• Text Tree: Human-readable hierarchical format\n" +
        "• JSON Export: Structured data for programmatic use\n" +
        "• Statistics Summary: Analysis metrics and recommendations\n\n" +
        
        "COMPARING DOCUMENTS:\n" +
        "1. Analyze first document and export results\n" +
        "2. Change document path to second document\n" +
        "3. Analyze second document and export results\n" +
        "4. Manually compare the exported files\n\n" +
        
        "For more detailed information, check the console output during analysis.",
        {multiline: true, readonly: true});
    helpText.alignment = "fill";
    
    var closeBtn = helpDialog.add("button", undefined, "Close");
    closeBtn.alignment = "center";
    closeBtn.onClick = function() {
        helpDialog.close();
    };
    
    helpDialog.show();
}

// ABOUT DIALOG - Tool information
function showAboutDialog() {
    var aboutDialog = new Window("dialog", "About InDesign Document Query Tool");
    aboutDialog.orientation = "column";
    aboutDialog.alignChildren = "center";
    aboutDialog.preferredSize.width = 450;
    aboutDialog.preferredSize.height = 350;
    
    var titleText = aboutDialog.add("statictext", undefined, "InDesign Document Query Tool");
    titleText.graphics.font = ScriptUI.newFont("Arial", ScriptUI.FontStyle.BOLD, 16);
    
    var versionText = aboutDialog.add("statictext", undefined, "Version 3.0 - Configurable Analysis");
    
    var descText = aboutDialog.add("statictext", undefined, 
        "A lightweight, modular tool for safely analyzing\n" +
        "InDesign document structures and properties.\n\n" +
        "Built with progressive safety architecture to prevent\n" +
        "hanging on problematic documents while providing\n" +
        "detailed insights into document composition.",
        {multiline: true});
    descText.alignment = "center";
    
    var featuresText = aboutDialog.add("statictext", undefined,
        "Key Features:\n" +
        "• ES3 Compatible ExtendScript\n" +
        "• Modular architecture with 5 core modules\n" +
        "• Real-time progress tracking\n" +
        "• Configurable safety controls\n" +
        "• DOM-like tree structure output\n" +
        "• Multiple export formats\n" +
        "• Preset configurations for common use cases",
        {multiline: true});
    
    var techText = aboutDialog.add("statictext", undefined,
        "Architecture: 5 ES3-compatible modules\n" +
        "• Module A: Configuration & Safety Framework\n" +
        "• Module B: Document Analysis & Tree Builder\n" +
        "• Module C: UI Panel & Controls\n" +
        "• Module D: Export & Results Display\n" +
        "• Module E: Main Entry Point",
        {multiline: true});
    
    var closeBtn = aboutDialog.add("button", undefined, "Close");
    closeBtn.onClick = function() {
        aboutDialog.close();
    };
    
    aboutDialog.show();
}

// UTILITIES FOR MAIN SCRIPT
function checkEnvironment() {
    var checks = {
        indesign: typeof app !== 'undefined' && app.name.indexOf("InDesign") !== -1,
        documents: app && app.documents !== undefined,
        filesystem: typeof File !== 'undefined' && typeof Folder !== 'undefined',
        ui: typeof Window !== 'undefined'
    };
    
    $.writeln("Environment check:");
    $.writeln("  InDesign App: " + (checks.indesign ? "✓" : "✗"));
    $.writeln("  Documents Access: " + (checks.documents ? "✓" : "✗"));
    $.writeln("  File System: " + (checks.filesystem ? "✓" : "✗"));
    $.writeln("  UI System: " + (checks.ui ? "✓" : "✗"));
    
    var allPassed = checks.indesign && checks.documents && checks.filesystem && checks.ui;
    $.writeln("  Overall: " + (allPassed ? "✓ Ready" : "✗ Issues detected"));
    
    return allPassed;
}

// ERROR HANDLING FOR MAIN SCRIPT
function handleScriptError(error, context) {
    var errorMsg = "InDesign Document Query Tool v3.0\n\n";
    errorMsg += "Error in " + (context || "main script") + ":\n";
    errorMsg += error.message + "\n\n";
    
    if (error.line) {
        errorMsg += "Line: " + error.line + "\n\n";
    }
    
    errorMsg += "Context: " + (context || "Unknown") + "\n";
    errorMsg += "This is a lightweight tool - try using simpler settings\n";
    errorMsg += "or check the ESTK console for detailed error information.";
    
    alert(errorMsg);
    
    $.writeln("=== SCRIPT ERROR ===");
    $.writeln("Context: " + (context || "main"));
    $.writeln("Message: " + error.message);
    if (error.line) $.writeln("Line: " + error.line);
    if (error.stack) $.writeln("Stack: " + error.stack);
    $.writeln("====================");
}

// MAIN SCRIPT EXECUTION
try {
    $.writeln("\n" + new Date().toString());
    $.writeln("Starting InDesign Document Query Tool v3.0...");
    
    // Environment check
    if (!checkEnvironment()) {
        throw new Error("Environment check failed - InDesign features not available");
    }
    
    // Initialize the tool
    initializeQueryTool();
    
} catch (mainError) {
    handleScriptError(mainError, "main initialization");
}

$.writeln("Module E: Main Entry Point loaded - Script ready for use");

// ==============================================================================
// BUILD VERIFICATION
// ==============================================================================

$.writeln("🎉 InDesign Query Tool v3.0 - All " + MODULES_LOADED.length + " modules loaded successfully!");
if (MODULES_LOADED.length === 5) {
    $.writeln("✅ Build verification passed - ready for use");
} else {
    $.writeln("⚠️  Module count mismatch - check for loading errors");
}
