#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

// Configuration
const TARGET_FOLDER = './scripts'; // Adjust if needed - current folder is '.'
const OUTPUT_FILE = 'InDesignDocInspectorAndComparer_ChunkBuilt.jsx';
const CHUNK_PATTERN = /^InDesignDocInspectorAndComparer_Chunk(\d+)_.*\.jsx$/;

console.log('🔧 InDesign Inspector Chunk Builder');
console.log('=====================================');

function discoverChunkFiles(folderPath) {
    try {
        const files = fs.readdirSync(folderPath);
        const chunkFiles = [];
        
        files.forEach(file => {
            const match = file.match(CHUNK_PATTERN);
            if (match) {
                const chunkNumber = parseInt(match[1]);
                const fullPath = path.join(folderPath, file);
                chunkFiles.push({
                    filename: file,
                    path: fullPath,
                    chunkNumber: chunkNumber
                });
                console.log(`📁 Found: ${file} (Chunk ${chunkNumber})`);
            }
        });
        
        // Sort by chunk number
        chunkFiles.sort((a, b) => a.chunkNumber - b.chunkNumber);
        
        return chunkFiles;
    } catch (error) {
        console.error(`❌ Error reading folder ${folderPath}:`, error.message);
        process.exit(1);
    }
}

function buildCombinedFile(chunkFiles, outputPath) {
    console.log('\n🔨 Building combined file...');
    
    let combinedContent = '';
    
    // Add header comment
    combinedContent += '//\n';
    combinedContent += '// Enhanced InDesign Document Inspector & Comparison Tool v2.1-ESTK\n';
    combinedContent += '// COMPLETE ASSEMBLED VERSION - All Chunks Combined\n';
    combinedContent += '// Generated: ' + new Date().toISOString() + '\n';
    combinedContent += '// \n';
    combinedContent += '// This file contains all ' + chunkFiles.length + ' chunks assembled in proper order:\n';
    
    chunkFiles.forEach((chunk, index) => {
        combinedContent += '// Chunk ' + (index + 1) + ': ' + chunk.filename + '\n';
    });
    
    combinedContent += '//\n';
    combinedContent += '// DO NOT EDIT THIS FILE DIRECTLY - Edit individual chunk files instead\n';
    combinedContent += '//\n\n';
    
    // Process each chunk file
    chunkFiles.forEach((chunk, index) => {
        console.log(`📝 Processing: ${chunk.filename}`);
        
        try {
            const content = fs.readFileSync(chunk.path, 'utf8');
            
            // Add chunk separator comment
            combinedContent += '// ' + '='.repeat(76) + '\n';
            combinedContent += '// CHUNK ' + (index + 1) + ': ' + chunk.filename.toUpperCase() + '\n';
            combinedContent += '// ' + '='.repeat(76) + '\n\n';
            
            // Add the chunk content
            combinedContent += content;
            
            // Add spacing between chunks (except after last chunk)
            if (index < chunkFiles.length - 1) {
                combinedContent += '\n\n';
            }
            
        } catch (error) {
            console.error(`❌ Error reading ${chunk.filename}:`, error.message);
            process.exit(1);
        }
    });
    
    // Write the combined file
    try {
        fs.writeFileSync(outputPath, combinedContent, 'utf8');
        console.log(`✅ Successfully created: ${outputPath}`);
        
        // Show file stats
        const stats = fs.statSync(outputPath);
        const sizeKB = Math.round(stats.size / 1024);
        console.log(`📊 File size: ${sizeKB} KB (${stats.size} bytes)`);
        console.log(`📊 Total chunks: ${chunkFiles.length}`);
        
    } catch (error) {
        console.error(`❌ Error writing ${outputPath}:`, error.message);
        process.exit(1);
    }
}

function validateChunkSequence(chunkFiles) {
    console.log('\n🔍 Validating chunk sequence...');
    
    if (chunkFiles.length === 0) {
        console.error('❌ No chunk files found matching pattern!');
        console.log('Expected pattern: InDesignDocInspectorAndComparer_Chunk[N]_*.jsx');
        process.exit(1);
    }
    
    // Check for missing chunks
    for (let i = 0; i < chunkFiles.length; i++) {
        const expectedChunk = i + 1;
        const actualChunk = chunkFiles[i].chunkNumber;
        
        if (actualChunk !== expectedChunk) {
            console.error(`❌ Missing chunk ${expectedChunk}! Found chunk ${actualChunk} instead.`);
            process.exit(1);
        }
    }
    
    console.log(`✅ Chunk sequence validated: ${chunkFiles.length} chunks found in correct order`);
    return true;
}

// Main execution
function main() {
    const targetFolder = process.argv[2] || TARGET_FOLDER;
    const outputFile = process.argv[3] || OUTPUT_FILE;
    
    console.log(`📂 Target folder: ${targetFolder}`);
    console.log(`📄 Output file: ${outputFile}`);
    console.log(`🔍 Pattern: ${CHUNK_PATTERN}\n`);
    
    // Check if target folder exists
    if (!fs.existsSync(targetFolder)) {
        console.error(`❌ Target folder does not exist: ${targetFolder}`);
        process.exit(1);
    }
    
    // Discover chunk files
    const chunkFiles = discoverChunkFiles(targetFolder);
    
    // Validate sequence
    validateChunkSequence(chunkFiles);
    
    // Build combined file
    buildCombinedFile(chunkFiles, outputFile);
    
    console.log('\n🎉 Build complete!');
    console.log(`\nNext steps:`);
    console.log(`1. Test the generated file: ${outputFile}`);
    console.log(`2. Copy to InDesign Scripts folder if needed`);
    console.log(`3. Run from ESTK or InDesign Scripts panel`);
}

// Run the script
if (require.main === module) {
    main();
}