//
// 5.0_dom-exporter.jsx
// InDesign DOM Discovery Builder - DOM Structure Export
// CORE PURPOSE: Export DOM structure to various file formats
// DEPENDENCIES: 1.0_safe-foundation.jsx, 2.0_dom-enumerator.jsx
// SAFETY: Uses only proven ExtendScript File operations
// ES3 COMPATIBLE: No reserved words, no modern JS features
//

// ============================================================================
// EXPORT CONFIGURATION
// ============================================================================

var EXPORT_CONFIG = {
    defaultFormat: 'text',
    maxFileSize: 5000000,  // 5MB limit
    includeMetadata: true,
    includeStatistics: true,
    includeAccessGuide: true,
    includeFullTree: true,
    lineSeparator: '\n'
};

// ============================================================================
// MAIN EXPORT FUNCTIONS
// ============================================================================

/**
 * Export DOM structure to file
 * @param {Object} domStructure - DOM structure object
 * @param {String} format - Export format: 'text'|'json'|'csv'
 * @param {String} customPath - Optional custom file path
 * @returns {Object} - {success: boolean, filePath: string, error: string}
 */
function exportDOMStructure(domStructure, format, customPath) {
    var result = {
        success: false,
        filePath: '',
        error: ''
    };
    
    try {
        if (!domStructure) {
            result.error = 'No DOM structure provided for export';
            return result;
        }
        
        var exportFormat = format || EXPORT_CONFIG.defaultFormat;
        
        // Generate export content based on format
        var content = '';
        var fileExtension = '.txt';
        
        switch (exportFormat.toLowerCase()) {
            case 'text':
                content = generateTextExport(domStructure);
                fileExtension = '.txt';
                break;
            case 'json':
                content = generateJSONExport(domStructure);
                fileExtension = '.json';
                break;
            case 'csv':
                content = generateCSVExport(domStructure);
                fileExtension = '.csv';
                break;
            default:
                result.error = 'Unsupported export format: ' + exportFormat;
                return result;
        }
        
        if (!content) {
            result.error = 'Failed to generate export content';
            return result;
        }
        
        // Check content size
        if (content.length > EXPORT_CONFIG.maxFileSize) {
            result.error = 'Export content too large (' + content.length + ' bytes). Consider reducing scope.';
            return result;
        }
        
        // Determine file path
        var filePath = customPath || generateDefaultFilePath(domStructure, fileExtension);
        
        // Write file
        var writeResult = writeToFile(filePath, content);
        if (writeResult.success) {
            result.success = true;
            result.filePath = writeResult.filePath;
            $.writeln('DOM structure exported successfully to: ' + result.filePath);
        } else {
            result.error = writeResult.error;
        }
        
    } catch (exc) {
        result.error = 'Export failed: ' + exc.message;
        $.writeln('ERROR: DOM export failed: ' + exc.message);
    }
    
    return result;
}

/**
 * Generate human-readable text export
 * @param {Object} domStructure - DOM structure to export
 * @returns {String} - Formatted text export
 */
function generateTextExport(domStructure) {
    var builder = createStringBuilder();
    
    // Header
    builder.appendLine('INDESIGN DOCUMENT DOM STRUCTURE ANALYSIS');
    builder.appendLine('=======================================');
    builder.appendLine('Generated by: InDesign DOM Discovery Builder v2.0');
    builder.appendLine('Timestamp: ' + getCurrentTimestamp());
    builder.appendLine('');
    
    // Document metadata
    if (EXPORT_CONFIG.includeMetadata && domStructure.metadata) {
        builder.appendLine('DOCUMENT INFORMATION');
        builder.appendLine('===================');
        builder.appendLine('Document Name: ' + (domStructure.metadata.documentName || 'Unknown'));
        builder.appendLine('Analysis Time: ' + (domStructure.metadata.enumerationTime || 0) + 'ms');
        builder.appendLine('Analysis Version: ' + (domStructure.metadata.version || 'Unknown'));
        
        if (domStructure.metadata.config) {
            builder.appendLine('');
            builder.appendLine('Analysis Configuration:');
            builder.appendLine('  Max Depth: ' + domStructure.metadata.config.maxDepth);
            builder.appendLine('  Timeout: ' + domStructure.metadata.config.timeoutMs + 'ms');
            builder.appendLine('  Skip Dangerous: ' + domStructure.metadata.config.skipDangerous);
            builder.appendLine('  Max Properties: ' + domStructure.metadata.config.maxProperties);
        }
        builder.appendLine('');
    }
    
    // Statistics
    if (EXPORT_CONFIG.includeStatistics && domStructure.statistics) {
        builder.appendLine('DISCOVERY STATISTICS');
        builder.appendLine('===================');
        builder.appendLine('Total Objects Discovered: ' + domStructure.statistics.totalNodes);
        builder.appendLine('Total Properties Found: ' + domStructure.statistics.totalProperties);
        builder.appendLine('Maximum Depth Reached: ' + domStructure.statistics.maxDepthReached);
        builder.appendLine('Circular References Detected: ' + domStructure.statistics.circularRefsDetected);
        builder.appendLine('Timeout Events: ' + domStructure.statistics.timeouts);
        builder.appendLine('Enumeration Errors: ' + domStructure.statistics.errors.length);
        
        // Property safety breakdown
        if (domStructure.structure && domStructure.structure.document) {
            var safetyCounts = countPropertiesBySafety(domStructure.structure.document);
            builder.appendLine('');
            builder.appendLine('Properties by Safety Level:');
            builder.appendLine('  Safe Properties: ' + safetyCounts.safe);
            builder.appendLine('  Moderate Risk Properties: ' + safetyCounts.moderate);
            builder.appendLine('  Risky Properties: ' + safetyCounts.risky);
            builder.appendLine('  Dangerous Properties: ' + safetyCounts.dangerous);
        }
        
        // Sampling statistics if available
        if (domStructure.metadata && domStructure.metadata.sampling) {
            var samplingStats = getSamplingStatistics(domStructure);
            builder.appendLine('');
            builder.appendLine('Property Value Sampling:');
            builder.appendLine('  Values Sampled: ' + samplingStats.successful + '/' + samplingStats.attempted);
            builder.appendLine('  Sampling Time: ' + samplingStats.samplingTime + 'ms');
            builder.appendLine('  Timeouts: ' + samplingStats.timeouts);
            builder.appendLine('  Errors: ' + samplingStats.errors);
        }
        
        builder.appendLine('');
    }
    
    // Property access guide
    if (EXPORT_CONFIG.includeAccessGuide) {
        builder.appendLine('PROPERTY ACCESS GUIDE');
        builder.appendLine('====================');
        builder.appendLine('This section shows how to safely access discovered properties in your own scripts.');
        builder.appendLine('');
        
        if (domStructure.structure && domStructure.structure.document) {
            var accessGuide = generatePropertyAccessGuide(domStructure.structure.document);
            builder.append(accessGuide);
        }
        
        builder.appendLine('');
    }
    
    // Full DOM tree structure
    if (EXPORT_CONFIG.includeFullTree) {
        builder.appendLine('COMPLETE DOM STRUCTURE');
        builder.appendLine('=====================');
        builder.appendLine('This tree shows all discovered objects and properties with their safety classifications.');
        builder.appendLine('');
        
        if (domStructure.structure && domStructure.structure.document) {
            var treeText = generateDetailedDOMTree(domStructure.structure.document, '', true);
            builder.append(treeText);
        } else {
            builder.appendLine('No DOM structure available');
        }
        
        builder.appendLine('');
    }
    
    // Footer with usage notes
    builder.appendLine('USAGE NOTES');
    builder.appendLine('===========');
    builder.appendLine('• This file contains the complete DOM structure discovered in your InDesign document');
    builder.appendLine('• Use the Property Access Guide section to write safe property access code');
    builder.appendLine('• Properties marked [safe] are recommended for direct access');
    builder.appendLine('• Properties marked [risky] or [dangerous] should be accessed with error handling');
    builder.appendLine('• Collections should be iterated safely with length checks and try-catch blocks');
    builder.appendLine('• Always test property access with your specific document types');
    builder.appendLine('');
    builder.appendLine('Generated by InDesign DOM Discovery Builder');
    builder.appendLine('For more information, visit: [project documentation]');
    
    return builder.toString();
}

/**
 * Generate JSON export
 * @param {Object} domStructure - DOM structure to export
 * @returns {String} - JSON formatted export
 */
function generateJSONExport(domStructure) {
    try {
        // Create a simplified version for JSON export
        var exportData = {
            metadata: domStructure.metadata || {},
            statistics: domStructure.statistics || {},
            structure: simplifyDOMForJSON(domStructure.structure)
        };
        
        // Convert to JSON string (ES3 compatible approach)
        return stringifyObject(exportData, 0);
        
    } catch (exc) {
        $.writeln('ERROR: JSON export failed: ' + exc.message);
        return '';
    }
}

/**
 * Generate CSV export
 * @param {Object} domStructure - DOM structure to export
 * @returns {String} - CSV formatted export
 */
function generateCSVExport(domStructure) {
    var builder = createStringBuilder();
    
    // CSV header
    builder.appendLine('ObjectPath,PropertyName,PropertyType,SafetyLevel,IsCollection,IsMethod,HasSampleValue,SampleValue');
    
    if (domStructure.structure && domStructure.structure.document) {
        generateCSVFromNode(domStructure.structure.document, builder);
    }
    
    return builder.toString();
}

// ============================================================================
// EXPORT UTILITIES
// ============================================================================

/**
 * Simplify DOM structure for JSON export
 * @param {Object} structure - DOM structure to simplify
 * @returns {Object} - Simplified structure
 */
function simplifyDOMForJSON(structure) {
    if (!structure) return {};
    
    var simplified = {};
    
    try {
        for (var key in structure) {
            if (structure[key] && typeof structure[key] === 'object') {
                simplified[key] = simplifyDOMNodeForJSON(structure[key]);
            } else {
                simplified[key] = structure[key];
            }
        }
    } catch (exc) {
        $.writeln('ERROR: Simplifying DOM for JSON: ' + exc.message);
    }
    
    return simplified;
}

/**
 * Simplify DOM node for JSON export
 * @param {Object} domNode - DOM node to simplify
 * @returns {Object} - Simplified node
 */
function simplifyDOMNodeForJSON(domNode) {
    if (!domNode) return null;
    
    var simplified = {
        name: domNode.name || '',
        path: domNode.path || '',
        type: domNode.type || '',
        depth: domNode.depth || 0,
        hasCircularRefs: domNode.hasCircularRefs || false
    };
    
    // Simplified properties
    if (domNode.properties && domNode.properties.length > 0) {
        simplified.properties = [];
        for (var i = 0; i < domNode.properties.length; i++) {
            var prop = domNode.properties[i];
            simplified.properties.push({
                name: prop.name,
                type: prop.type,
                safetyLevel: prop.safetyLevel,
                isCollection: prop.isCollection || false,
                isMethod: prop.isMethod || false
            });
        }
    }
    
    // Simplified collections
    if (domNode.collections && domNode.collections.length > 0) {
        simplified.collections = [];
        for (var i = 0; i < domNode.collections.length; i++) {
            var coll = domNode.collections[i];
            simplified.collections.push({
                name: coll.name,
                type: coll.type,
                safetyLevel: coll.safetyLevel
            });
        }
    }
    
    return simplified;
}

/**
 * Generate CSV rows from DOM node
 * @param {Object} domNode - DOM node to process
 * @param {Object} builder - String builder for output
 */
function generateCSVFromNode(domNode, builder) {
    if (!domNode) return;
    
    // Process properties
    if (domNode.properties) {
        for (var i = 0; i < domNode.properties.length; i++) {
            var prop = domNode.properties[i];
            var sampleValue = prop.hasSampleValue ? prop.sampleValue : '';
            var csvLine = '"' + (domNode.path || '') + '","' + prop.name + '","' + prop.type + '","' + 
                         prop.safetyLevel + '","' + (prop.isCollection ? 'true' : 'false') + '","' + 
                         (prop.isMethod ? 'true' : 'false') + '","' + (prop.hasSampleValue ? 'true' : 'false') + 
                         '","' + escapeCsvValue(sampleValue) + '"';
            builder.appendLine(csvLine);
        }
    }
    
    // Process collections
    if (domNode.collections) {
        for (var i = 0; i < domNode.collections.length; i++) {
            var coll = domNode.collections[i];
            var sampleValue = coll.hasSampleValue ? coll.sampleValue : '';
            var csvLine = '"' + (domNode.path || '') + '","' + coll.name + '","' + coll.type + '","' + 
                         coll.safetyLevel + '","true","false","' + (coll.hasSampleValue ? 'true' : 'false') + 
                         '","' + escapeCsvValue(sampleValue) + '"';
            builder.appendLine(csvLine);
        }
    }
    
    // Process child nodes recursively
    if (domNode.childNodes) {
        for (var i = 0; i < domNode.childNodes.length; i++) {
            generateCSVFromNode(domNode.childNodes[i], builder);
        }
    }
}

/**
 * Escape CSV value for safe output
 * @param {String} value - Value to escape
 * @returns {String} - Escaped value
 */
function escapeCsvValue(value) {
    if (!value) return '';
    var str = String(value);
    // Replace quotes with double quotes and wrap in quotes if contains comma or quote
    str = str.replace(/"/g, '""');
    if (str.indexOf(',') !== -1 || str.indexOf('"') !== -1 || str.indexOf('\n') !== -1) {
        str = '"' + str + '"';
    }
    return str;
}

/**
 * Generate property access guide
 * @param {Object} domNode - DOM node to analyze
 * @returns {String} - Property access guide
 */
function generatePropertyAccessGuide(domNode) {
    var builder = createStringBuilder();
    
    builder.appendLine('SAFE PROPERTY ACCESS EXAMPLES:');
    builder.appendLine('------------------------------');
    
    // Find safe properties for examples
    var safeProperties = findSafeProperties(domNode);
    
    if (safeProperties.length > 0) {
        builder.appendLine('// Basic safe properties:');
        for (var i = 0; i < Math.min(safeProperties.length, 8); i++) {
            var prop = safeProperties[i];
            var varName = prop.name.replace(/[^a-zA-Z0-9]/g, '');
            var accessCode = 'var ' + varName + ' = document.' + prop.name + ';';
            var comment = '  // ' + prop.type + ' - ' + prop.safetyLevel;
            builder.appendLine(accessCode + comment);
        }
    } else {
        builder.appendLine('// No safe properties found for direct access');
    }
    
    builder.appendLine('');
    builder.appendLine('COLLECTION ACCESS PATTERNS:');
    builder.appendLine('---------------------------');
    
    // Find collections for examples
    var collections = findCollections(domNode);
    
    if (collections.length > 0) {
        for (var i = 0; i < Math.min(collections.length, 3); i++) {
            var collection = collections[i];
            builder.appendLine('// Access ' + collection.name + ' collection safely:');
            builder.appendLine('try {');
            builder.appendLine('  var ' + collection.name + ' = document.' + collection.name + ';');
            builder.appendLine('  if (' + collection.name + ' && ' + collection.name + '.length > 0) {');
            builder.appendLine('    for (var i = 0; i < ' + collection.name + '.length; i++) {');
            builder.appendLine('      var item = ' + collection.name + '[i];');
            builder.appendLine('      // Process item safely');
            builder.appendLine('    }');
            builder.appendLine('  }');
            builder.appendLine('} catch (exc) {');
            builder.appendLine('  // Handle collection access error');
            builder.appendLine('}');
            builder.appendLine('');
        }
    }
    
    builder.appendLine('SAFETY RECOMMENDATIONS:');
    builder.appendLine('-----------------------');
    builder.appendLine('• Always wrap property access in try-catch blocks');
    builder.appendLine('• Check for null/undefined before accessing nested properties');
    builder.appendLine('• Use length checks before iterating collections');
    builder.appendLine('• Test with different document types and states');
    builder.appendLine('• Consider timeouts for operations on large collections');
    builder.appendLine('');
    
    return builder.toString();
}

/**
 * Find safe properties in DOM node
 * @param {Object} domNode - DOM node to search
 * @returns {Array} - Array of safe properties
 */
function findSafeProperties(domNode) {
    var safeProps = [];
    
    if (domNode && domNode.properties) {
        for (var i = 0; i < domNode.properties.length; i++) {
            var prop = domNode.properties[i];
            if (prop.safetyLevel === 'safe') {
                safeProps.push(prop);
            }
        }
    }
    
    return safeProps;
}

/**
 * Find collections in DOM node
 * @param {Object} domNode - DOM node to search
 * @returns {Array} - Array of collection properties
 */
function findCollections(domNode) {
    var collections = [];
    
    if (domNode && domNode.collections) {
        for (var i = 0; i < domNode.collections.length; i++) {
            collections.push(domNode.collections[i]);
        }
    }
    
    return collections;
}

/**
 * Generate detailed DOM tree for export
 * @param {Object} domNode - DOM node to format
 * @param {String} prefix - Current line prefix
 * @param {Boolean} isLast - Whether this is the last child
 * @returns {String} - Formatted tree text
 */
function generateDetailedDOMTree(domNode, prefix, isLast) {
    var builder = createStringBuilder();
    
    if (!domNode) return '';
    
    // Current node
    var nodePrefix = prefix + (isLast ? '└── ' : '├── ');
    var nodeLine = nodePrefix + domNode.name + ' (' + domNode.type + ')';
    if (domNode.hasCircularRefs) nodeLine += ' [CIRCULAR]';
    builder.appendLine(nodeLine);
    
    var childPrefix = prefix + (isLast ? '    ' : '│   ');
    
    // Properties (show all, not limited like in UI)
    if (domNode.properties && domNode.properties.length > 0) {
        for (var i = 0; i < domNode.properties.length; i++) {
            var prop = domNode.properties[i];
            var propPrefix = childPrefix + (i < domNode.properties.length - 1 ? '├── ' : '└── ');
            var propLine = propPrefix + prop.name + ' (' + prop.type + ') [' + prop.safetyLevel + ']';
            
            if (prop.hasSampleValue && prop.sampleValue) {
                propLine += ' = ' + prop.sampleValue;
            }
            
            builder.appendLine(propLine);
        }
    }
    
    // Collections
    if (domNode.collections && domNode.collections.length > 0) {
        for (var i = 0; i < domNode.collections.length; i++) {
            var collection = domNode.collections[i];
            var collPrefix = childPrefix + '├── ';
            var collLine = collPrefix + collection.name + ' (' + collection.type + ') [' + collection.safetyLevel + '] [COLLECTION]';
            
            if (collection.hasSampleValue && collection.sampleValue) {
                collLine += ' = ' + collection.sampleValue;
            }
            
            builder.appendLine(collLine);
        }
    }
    
    return builder.toString();
}

// ============================================================================
// FILE OPERATIONS
// ============================================================================

/**
 * Write content to file using proven ExtendScript patterns
 * @param {String} filePath - Path to write file
 * @param {String} content - Content to write
 * @returns {Object} - {success: boolean, filePath: string, error: string}
 */
function writeToFile(filePath, content) {
    var result = {
        success: false,
        filePath: '',
        error: ''
    };
    
    try {
        var file = new File(filePath);
        
        if (!file.open('w')) {
            result.error = 'Cannot open file for writing: ' + filePath;
            return result;
        }
        
        if (!file.write(content)) {
            result.error = 'Failed to write content to file';
            file.close();
            return result;
        }
        
        file.close();
        
        result.success = true;
        result.filePath = file.absoluteURI;
        
    } catch (exc) {
        result.error = 'File operation failed: ' + exc.message;
    }
    
    return result;
}

/**
 * Generate default file path
 * @param {Object} domStructure - DOM structure for naming
 * @param {String} extension - File extension
 * @returns {String} - Generated file path
 */
function generateDefaultFilePath(domStructure, extension) {
    try {
        var docName = 'InDesignDocument';
        
        if (domStructure.metadata && domStructure.metadata.documentName) {
            docName = domStructure.metadata.documentName.replace(/[^a-zA-Z0-9]/g, '_');
        }
        
        var timestamp = new Date();
        var timeStr = timestamp.getFullYear() + 
                     ('0' + (timestamp.getMonth() + 1)).slice(-2) + 
                     ('0' + timestamp.getDate()).slice(-2) + '_' +
                     ('0' + timestamp.getHours()).slice(-2) + 
                     ('0' + timestamp.getMinutes()).slice(-2);
        
        var fileName = docName + '_DOM_' + timeStr + extension;
        
        // Try to place next to document if possible
        var envResult = validateInDesignEnvironment();
        if (envResult.valid && envResult.document) {
            try {
                // Try to get document file path safely
                var docFilePath = null;
                if (safeTypeCheck(envResult.document, 'filePath') === 'string') {
                    docFilePath = envResult.document.filePath;
                } else if (safeTypeCheck(envResult.document, 'fullName') === 'object') {
                    // Try fullName property which might be a File object
                    var fullNameObj = envResult.document.fullName;
                    if (fullNameObj && safeTypeCheck(fullNameObj, 'parent') === 'object') {
                        var parentFolder = fullNameObj.parent;
                        if (parentFolder && safeTypeCheck(parentFolder, 'absoluteURI') === 'string') {
                            return parentFolder.absoluteURI + '/' + fileName;
                        }
                    }
                }
                
                if (docFilePath) {
                    var docFile = new File(docFilePath);
                    if (docFile.parent && docFile.parent.exists) {
                        return docFile.parent.absoluteURI + '/' + fileName;
                    }
                }
            } catch (exc) {
                // Fall through to desktop if document path access fails
                $.writeln('Could not access document path, using desktop: ' + exc.message);
            }
        }
        
        // Default to desktop
        return Folder.desktop.absoluteURI + '/' + fileName;
        
    } catch (exc) {
        return Folder.desktop.absoluteURI + '/InDesignDOM_export' + extension;
    }
}

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

/**
 * Simple object stringification for ES3 compatibility
 * @param {*} obj - Object to stringify
 * @param {Number} depth - Current depth
 * @returns {String} - JSON-like string
 */
function stringifyObject(obj, depth) {
    // Simple implementation - could be enhanced
    if (depth > 3) return '"[max depth]"';
    
    if (obj === null) return 'null';
    if (obj === undefined) return 'undefined';
    
    var type = typeof obj;
    
    if (type === 'string') return '"' + obj.replace(/"/g, '\\"') + '"';
    if (type === 'number' || type === 'boolean') return String(obj);
    
    if (type === 'object') {
        if (obj.constructor === Array || (obj.length !== undefined && typeof obj.length === 'number')) {
            // Handle arrays
            var parts = ['['];
            var arrayLength = obj.length || 0;
            for (var i = 0; i < Math.min(arrayLength, 10); i++) {  // Limit array size
                if (i > 0) parts.push(',');
                parts.push(stringifyObject(obj[i], depth + 1));
            }
            if (arrayLength > 10) parts.push(',"[...more items]"');
            parts.push(']');
            return parts.join('');
        } else {
            // Handle objects
            var parts = ['{'];
            var first = true;
            var count = 0;
            for (var key in obj) {
                if (count >= 20) {  // Limit object properties
                    if (!first) parts.push(',');
                    parts.push('"[...more properties]":"truncated"');
                    break;
                }
                if (!first) parts.push(',');
                parts.push('"' + key + '":');
                parts.push(stringifyObject(obj[key], depth + 1));
                first = false;
                count++;
            }
            parts.push('}');
            return parts.join('');
        }
    }
    
    return '"[' + type + ']"';
}

// ============================================================================
// MODULE INITIALIZATION
// ============================================================================

/**
 * Initialize DOM exporter module
 * @returns {Boolean} - true if initialization successful
 */
function initializeDOMExporter() {
    try {
        // Check dependencies
        if (typeof createStringBuilder !== 'function') {
            $.writeln('ERROR: Safe foundation module not loaded');
            return false;
        }
        
        // Test core functions
        var requiredFunctions = [
            'exportDOMStructure', 'generateTextExport', 'writeToFile'
        ];
        
        for (var i = 0; i < requiredFunctions.length; i++) {
            if (typeof eval(requiredFunctions[i]) !== 'function') {
                $.writeln('ERROR: Required function missing: ' + requiredFunctions[i]);
                return false;
            }
        }
        
        $.writeln('5.0_dom-exporter.jsx: All functions initialized successfully');
        $.writeln('Use exportDOMStructure(domStructure, format) to export DOM data');
        return true;
        
    } catch (exc) {
        $.writeln('ERROR: DOM exporter initialization failed: ' + exc.message);
        return false;
    }
}

// Auto-initialize when module loads
initializeDOMExporter();